### ISSUE TITLE
crash using `engine='scad'` with boolean operations

### ISSUE THREAD

**Issue by DustinReagan** [mikedh/trimesh#1037]
I've installed OpenSCAD,  yet I get the following crash when i switch to `engine='scad'`:

```
Traceback (most recent call last):
  File "src/app/find_border.py", line 97, in <module>
    diff = new_mesh.difference(inner, engine='scad')
  File "/opt/miniconda3/envs/hfh/lib/python3.7/site-packages/trimesh/base.py", line 2616, in difference
    engine=engine, **kwargs)
  File "/opt/miniconda3/envs/hfh/lib/python3.7/site-packages/trimesh/boolean.py", line 25, in difference
    result = _engines[engine](meshes, operation='difference', **kwargs)
  File "/opt/miniconda3/envs/hfh/lib/python3.7/site-packages/trimesh/interfaces/scad.py", line 65, in boolean
    return interface_scad(meshes, script, debug=debug, **kwargs)
  File "/opt/miniconda3/envs/hfh/lib/python3.7/site-packages/trimesh/interfaces/scad.py", line 53, in interface_scad
    result = scad.run(_scad_executable + ' $SCRIPT -o $MESH_POST')
  File "/opt/miniconda3/envs/hfh/lib/python3.7/site-packages/trimesh/interfaces/generic.py", line 90, in run
    startupinfo=startupinfo)
  File "/opt/miniconda3/envs/hfh/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Applications/OpenSCAD.app/Contents/MacOS/openscad', '/var/folders/k3/hfd_v6x52mqcvp2cxpllyh0c0000gn/T/tmpkpnv5evr', '-o', '/var/folders/k3/hfd_v6x52mqcvp2cxpllyh0c0000gn/T/tmpb87_spjh.off']' returned non-zero exit status 1.
```

BTW, the same code when using `engine='blender'`.

Any ideas?

**Comment by mikedh** [comment]
Hey, yeah the interfaces aren't super well tested on Mac. What does it say if you run in debug mode:

```
In [1]: import trimesh
 
In [2]: a = trimesh.load('models/ballA.off')

In [3]: b = trimesh.load('models/ballB.off')

In [4]: c = a.difference(b)

In [5]: c = a.difference(b, debug=True)
Blender 2.90.1 (hash 3e85bb34d0d7 built 2020-09-23 08:34:47)
/run/user/1001/snap.blender/gvfs/ non-existent directory
found bundled python: /snap/blender/47/2.90/python
Info: Deleted 3 object(s)
Info: Deleted 3 object(s)
Import finished in 0.0184 sec.
Import finished in 0.0176 sec.
Info: Deleted 1 object(s)
Info: Deleted 1 object(s)

Blender quit


```

**Comment by DustinReagan** [comment]
With Blender:
```
diff = new_mesh.difference(inner, engine='blender', debug=True)
...
Blender 2.83.5 (hash c2b144df395f built 2020-08-19 06:08:34)
Read prefs: /Users/dustinreagan/Library/Application Support/Blender/2.83/config/userpref.blend
found bundled python: /Applications/blender.app/Contents/Resources/2.83/python
Info: Deleted 3 object(s)
Info: Deleted 3 object(s)
Import finished in 4.4552 sec.
Import finished in 0.1551 sec.
Info: Deleted 1 object(s)
Info: Deleted 1 object(s)
```

With OpenSCAD:
```
diff = new_mesh.difference(inner, engine='scad', debug=True)
...
Current top level object is empty.
Traceback (most recent call last):
  File "src/app/find_border.py", line 97, in <module>
    diff = new_mesh.difference(inner, engine='scad', debug=True)
  File "/opt/miniconda3/envs/hfh/lib/python3.7/site-packages/trimesh/base.py", line 2616, in difference
    engine=engine, **kwargs)
  File "/opt/miniconda3/envs/hfh/lib/python3.7/site-packages/trimesh/boolean.py", line 25, in difference
    result = _engines[engine](meshes, operation='difference', **kwargs)
  File "/opt/miniconda3/envs/hfh/lib/python3.7/site-packages/trimesh/interfaces/scad.py", line 65, in boolean
    return interface_scad(meshes, script, debug=debug, **kwargs)
  File "/opt/miniconda3/envs/hfh/lib/python3.7/site-packages/trimesh/interfaces/scad.py", line 53, in interface_scad
    result = scad.run(_scad_executable + ' $SCRIPT -o $MESH_POST')
  File "/opt/miniconda3/envs/hfh/lib/python3.7/site-packages/trimesh/interfaces/generic.py", line 90, in run
    startupinfo=startupinfo)
  File "/opt/miniconda3/envs/hfh/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Applications/OpenSCAD.app/Contents/MacOS/openscad', '/var/folders/k3/hfd_v6x52mqcvp2cxpllyh0c0000gn/T/tmpv2k5cvj1', '-o', '/var/folders/k3/hfd_v6x52mqcvp2cxpllyh0c0000gn/T/tmpc03y4a9c.off']' returned non-zero exit status 1.
```

**Comment by DustinReagan** [comment]
> Hey, yeah the interfaces aren't super well tested on Mac. What does it say if you run in debug mode:

What is the preferred/best-tested environment to do boolean ops on?

**Comment by mikedh** [comment]
I usually develop on Ubuntu LTS, even on my Macbook I use a Parallels Desktop Ubuntu 20.04 VM.

**Comment by Aniwax** [comment]
I have a more general question regarding using Blender or openscad engine for boolean operations: Do I need to startup the blender engine first and then do an operation? 

Because I have a for loop, which does two boolean operations every iterations. The runtime was suprisingly slow. I wonder if I should initialise the engine first.

My code is like this:
`for number_of_grains in number:
    start_time = time.time()
    list_of_grain, Block= getsetup(number_of_grains,distance)
    union_list_of_balls = trimesh.boolean.union(list_of_grain, engine="blender")
    residual_box_block = trimesh.boolean.difference([Block, union_list_of_balls], engine="blender")
    end_time = time.time()
    this_process_time = end_time-start_time
    run_time_collection.append(this_process_time)`

**Comment by dlednik** [comment]
FYI:
I also get a crash using scad engine on Ubuntu 18.04LTS

**Comment by dlednik** [comment]
@Aniwax I saw same performance issues in my co2tools library. But I found out if I use multithreading to join the items together and then do difference on just 2 objects it is much faster than sending a list of meshes to cut out.

you can have a look at a sample loop code here:
https://github.com/Mambix/co2tools/blob/master/co2tools/stl/builder.py#L145
and this is where the union is called in a thread:
https://github.com/Mambix/co2tools/blob/master/co2tools/stl/builder.py#L157
