### ISSUE TITLE
Support for OBJ files with `\` (backslash) as line continuation character

### ISSUE THREAD

**Issue by hawkaa** [mikedh/trimesh#1103]
According to [this link](http://www.fileformat.info/format/wavefrontobj/egff.htm 13) and also some OBJ files I've seen, one can use a `\` (backslash) to split up elements in an OBJ file across several lines. However, trimesh does not support this in it's OBJ parser.

---

Trimesh version: 3.8.19
Python version: 3.8

Code:

```python
import trimesh
if __name__ == "__main__":
    mesh = trimesh.load("wallhole.obj", force='mesh')
```

Output:

```sh
unable to load materials from: 00.mtl
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    mesh = trimesh.load("wallhole.obj", force='mesh')
  File "/Users/hakon/tmp/tri/venv/lib/python3.8/site-packages/trimesh/exchange/load.py", line 124, in load
    loaded = load_mesh(file_obj,
  File "/Users/hakon/tmp/tri/venv/lib/python3.8/site-packages/trimesh/constants.py", line 134, in timed
    result = method(*args, **kwargs)
  File "/Users/hakon/tmp/tri/venv/lib/python3.8/site-packages/trimesh/exchange/load.py", line 206, in load_mesh
    results = mesh_loaders[file_type](file_obj,
  File "/Users/hakon/tmp/tri/venv/lib/python3.8/site-packages/trimesh/exchange/obj.py", line 150, in load_obj
    faces, faces_tex, faces_norm = _parse_faces_fallback(face_lines)
  File "/Users/hakon/tmp/tri/venv/lib/python3.8/site-packages/trimesh/exchange/obj.py", line 467, in _parse_faces_fallback
    v.append(int(split[0]))
ValueError: invalid literal for int() with base 10: '\\'
```

Wallhole.obj:
```obj
# Rhino

mtllib 00.mtl
usemtl 
v 0 0 0
v 0 10 0
v 10 0 0
v 10 10 0
v 5 0 0
v 10 5 0
v 5 10 0
v 0 5 0
v 10 0 0
v 10 10 0
v 10 0 -10
v 10 10 -10
v 10 5 0
v 10 0 -4
v 10 5 -10
v 10 10 -5
v 10 5 -4
v 10 5 -6
v 10 0 -6
v 10 0 -10
v 10 10 -10
v 0 0 -10
v 0 10 -10
v 10 5 -10
v 5 0 -10
v 0 5 -10
v 5 10 -10
v 0 0 -4
v 0 5 -4
v 10 0 -4
v 10 5 -4
v 5 5 -4
v 5 0 -4
v 10 0 -6
v 10 5 -6
v 0 0 -6
v 0 5 -6
v 5 5 -6
v 5 0 -6
v 0 5 -4
v 0 5 -6
v 10 5 -4
v 10 5 -6
v 5 5 -4
v 5 5 -6
v 0 0 -10
v 0 10 -10
v 0 0 0
v 0 10 0
v 0 5 0
v 0 5 -10
v 0 0 -6
v 0 10 -5
v 0 5 -4
v 0 0 -4
v 0 5 -6
v 0 0 0
v 0 0 -4
v 10 0 0
v 10 0 -4
v 5 0 0
v 5 0 -4
v 0 0 -6
v 0 0 -10
v 10 0 -6
v 10 0 -10
v 5 0 -10
v 5 0 -6
v 10 10 -10
v 0 10 -10
v 5 10 -10
v 2.5 12.5 -7.5
v 5 15 -5
v 7.5 12.5 -7.5
v 0 10 -10
v 0 10 0
v 0 10 -5
v 5 15 -5
v 2.5 12.5 -7.5
v 2.5 12.5 -2.5
v 0 10 0
v 10 10 0
v 5 10 0
v 5 15 -5
v 2.5 12.5 -2.5
v 7.5 12.5 -2.5
v 10 10 0
v 10 10 -10
v 10 10 -5
v 7.5 12.5 -7.5
v 5 15 -5
v 7.5 12.5 -2.5
vt 0.58578646183013916 0.41421356797218323
vt 0.29289323091506958 0.41421356797218323
vt 0.58578646183013916 0.70564192533493042
vt 0.29289323091506958 0.70564192533493042
vt 0.58578646183013916 0.55992776155471802
vt 0.43933981657028198 0.70564192533493042
vt 0.29289323091506958 0.55992776155471802
vt 0.43933981657028198 0.41421356797218323
vt 0.93787497282028198 0.5
vt 0.6464465856552124 0.5
vt 0.93787497282028198 0.79289323091506958
vt 0.6464465856552124 0.79289323091506958
vt 0.79216080904006958 0.5
vt 0.93787497282028198 0.61715728044509888
vt 0.79216080904006958 0.79289323091506958
vt 0.6464465856552124 0.6464465856552124
vt 0.79216080904006958 0.61715728044509888
vt 0.79216080904006958 0.6757359504699707
vt 0.93787497282028198 0.6757359504699707
vt 0.93787497282028198 0
vt 0.6464465856552124 0
vt 0.93787497282028198 0.29289323091506958
vt 0.6464465856552124 0.29289323091506958
vt 0.79216080904006958 0
vt 0.93787497282028198 0.14644661545753479
vt 0.79216080904006958 0.29289323091506958
vt 0.6464465856552124 0.14644661545753479
vt 0.43787497282028198 0.70710676908493042
vt 0.29289323091506958 0.70710676908493042
vt 0.43787497282028198 0.99853515625
vt 0.29289323091506958 0.99853515625
vt 0.29289323091506958 0.8528209924697876
vt 0.43787497282028198 0.8528209924697876
vt 0 0.53753703832626343
vt 0 0.68398362398147583
vt 0.29142838716506958 0.53753703832626343
vt 0.29142838716506958 0.68398362398147583
vt 0.14571419358253479 0.68398362398147583
vt 0.14571419358253479 0.53753703832626343
vt 0 0
vt 0 0.058578643947839737
vt 0.29289323091506958 0
vt 0.29289323091506958 0.058578643947839737
vt 0.14644661545753479 0
vt 0.14644661545753479 0.058578643947839737
vt 0.29142838716506958 0.69169133901596069
vt 0 0.69169133901596069
vt 0.29142838716506958 0.98458456993103027
vt 0 0.98458456993103027
vt 0.14571419358253479 0.98458456993103027
vt 0.14571419358253479 0.69169133901596069
vt 0.29142838716506958 0.80884861946105957
vt 0 0.83813798427581787
vt 0.14571419358253479 0.8674272894859314
vt 0.29142838716506958 0.8674272894859314
vt 0.14571419358253479 0.80884861946105957
vt 0 0.41421356797218323
vt 0 0.53137087821960449
vt 0.29142838716506958 0.41421356797218323
vt 0.29142838716506958 0.53137087821960449
vt 0.14571419358253479 0.41421356797218323
vt 0.14571419358253479 0.53137087821960449
vt 0 0.063378684222698212
vt 0 0.18053597211837769
vt 0.29289323091506958 0.063378684222698212
vt 0.29289323091506958 0.18053597211837769
vt 0.14644661545753479 0.18053597211837769
vt 0.14644661545753479 0.063378684222698212
vt 0 0.19013606011867523
vt 0.29289323091506958 0.19013606011867523
vt 0.14644661545753479 0.19013606011867523
vt 0.21966990828514099 0.29368945956230164
vt 0.14644661545753479 0.39724284410476685
vt 0.073223307728767395 0.29368945956230164
vt 0.6449817419052124 0.70710676908493042
vt 0.6449817419052124 0.99853515625
vt 0.6449817419052124 0.8528209924697876
vt 0.43933981657028198 0.8528209924697876
vt 0.54216080904006958 0.77996385097503662
vt 0.54216080904006958 0.9256780743598938
vt 0.3232232928276062 0
vt 0.61611652374267578 0
vt 0.46966990828514099 0
vt 0.46966990828514099 0.20564194023609161
vt 0.39644661545753479 0.10282097011804581
vt 0.54289323091506958 0.10282097011804581
vt 0.3232232928276062 0.20710678398609161
vt 0.61611652374267578 0.20710678398609161
vt 0.46966990828514099 0.20710678398609161
vt 0.54289323091506958 0.30992776155471802
vt 0.46966990828514099 0.41274872422218323
vt 0.39644661545753479 0.30992776155471802
vn 0 0 1
vn 0 0 1
vn 0 0 1
vn 0 0 1
vn 0 0 1
vn 0 0 1
vn 0 0 1
vn 0 0 1
vn 1 0 0
vn 1 0 0
vn 1 0 0
vn 1 0 0
vn 1 0 0
vn 1 0 0
vn 1 0 0
vn 1 0 0
vn 1 0 0
vn 1 0 0
vn 1 0 0
vn 0 0 -1
vn 0 0 -1
vn 0 0 -1
vn 0 0 -1
vn 0 0 -1
vn 0 0 -1
vn 0 0 -1
vn 0 0 -1
vn 0 0 -1
vn 0 0 -1
vn 0 0 -1
vn 0 0 -1
vn 0 0 -1
vn 0 0 -1
vn 0 0 1
vn 0 0 1
vn 0 0 1
vn 0 0 1
vn 0 0 1
vn 0 0 1
vn 0 -1 0
vn 0 -1 0
vn 0 -1 0
vn 0 -1 0
vn 0 -1 0
vn 0 -1 0
vn -1 0 0
vn -1 0 0
vn -1 0 0
vn -1 0 0
vn -1 0 0
vn -1 0 0
vn -1 0 0
vn -1 0 0
vn -1 0 0
vn -1 0 0
vn -1 0 0
vn 0 -1 0
vn 0 -1 0
vn 0 -1 0
vn 0 -1 0
vn 0 -1 0
vn 0 -1 0
vn 0 -1 0
vn 0 -1 0
vn 0 -1 0
vn 0 -1 0
vn 0 -1 0
vn 0 -1 0
vn 0 0.70710676908493042 -0.70710676908493042
vn 0 0.70710676908493042 -0.70710676908493042
vn 0 0.70710676908493042 -0.70710676908493042
vn 0 0.70710676908493042 -0.70710676908493042
vn 0 0.70710676908493042 -0.70710676908493042
vn 0 0.70710676908493042 -0.70710676908493042
vn -0.70710676908493042 0.70710676908493042 0
vn -0.70710676908493042 0.70710676908493042 0
vn -0.70710676908493042 0.70710676908493042 0
vn -0.70710676908493042 0.70710676908493042 0
vn -0.70710676908493042 0.70710676908493042 0
vn -0.70710676908493042 0.70710676908493042 0
vn 0 0.70710676908493042 0.70710676908493042
vn 0 0.70710676908493042 0.70710676908493042
vn 0 0.70710676908493042 0.70710676908493042
vn 0 0.70710676908493042 0.70710676908493042
vn 0 0.70710676908493042 0.70710676908493042
vn 0 0.70710676908493042 0.70710676908493042
vn 0.70710676908493042 0.70710676908493042 0
vn 0.70710676908493042 0.70710676908493042 0
vn 0.70710676908493042 0.70710676908493042 0
vn 0.70710676908493042 0.70710676908493042 0
vn 0.70710676908493042 0.70710676908493042 0
vn 0.70710676908493042 0.70710676908493042 0
f 8/8/8 1/1/1 5/5/5 3/3/3 6/6/6 4/4/4 7/7/7 2/2/2
f 14/14/14 17/17/17 18/18/18 19/19/19 11/11/11 15/15/15 12/12/12 \
16/16/16 10/10/10 13/13/13 9/9/9
f 24/24/24 20/20/20 25/25/25 22/22/22 26/26/26 23/23/23 27/27/27 \
21/21/21
f 29/29/29 32/32/32 31/31/31 30/30/30 33/33/33 28/28/28
f 35/35/35 38/38/38 37/37/37 36/36/36 39/39/39 34/34/34
f 41/41/41 45/45/45 43/43/43 42/42/42 44/44/44 40/40/40
f 52/52/52 56/56/56 54/54/54 55/55/55 48/48/48 50/50/50 49/49/49 \
53/53/53 47/47/47 51/51/51 46/46/46
f 58/58/58 62/62/62 60/60/60 59/59/59 61/61/61 57/57/57
f 64/64/64 67/67/67 66/66/66 65/65/65 68/68/68 63/63/63
f 74/74/74 69/69/69 71/71/71 70/70/70 72/72/72 73/73/73
f 75/75/75 77/77/77 76/76/76 80/80/80 78/78/78 79/79/79
f 84/84/84 85/85/85 81/81/81 83/83/83 82/82/82 86/86/86
f 92/92/92 87/87/87 89/89/89 88/88/88 90/90/90 91/91/91
```

**Comment by mikedh** [comment]
Your fix should be released now- thanks for the PR!
