### ISSUE TITLE
can not export obj file

### ISSUE THREAD

**Issue by iamnotstone** [mikedh/trimesh#1110]
I met the same problem like here #1033 . below is my obj file:

box.obj:
```
# Blender v2.82 (sub 7) OBJ File: ''
# www.blender.org
mtllib box.mtl
o Cube
v 1.000000 1.000000 -1.000000
v 1.000000 -1.000000 -1.000000
v 1.000000 1.000000 1.000000
v 1.000000 -1.000000 1.000000
v -1.000000 1.000000 -1.000000
v -1.000000 -1.000000 -1.000000
v -1.000000 1.000000 1.000000
v -1.000000 -1.000000 1.000000
vt 0.625000 0.500000
vt 0.875000 0.500000
vt 0.875000 0.750000
vt 0.625000 0.750000
vt 0.375000 0.750000
vt 0.625000 1.000000
vt 0.375000 1.000000
vt 0.375000 0.000000
vt 0.625000 0.000000
vt 0.625000 0.250000
vt 0.375000 0.250000
vt 0.125000 0.500000
vt 0.375000 0.500000
vt 0.125000 0.750000
vn 0.0000 1.0000 0.0000
vn 0.0000 0.0000 1.0000
vn -1.0000 0.0000 0.0000
vn 0.0000 -1.0000 0.0000
vn 1.0000 0.0000 0.0000
vn 0.0000 0.0000 -1.0000
usemtl Material
s off
f 1/1/1 5/2/1 7/3/1 3/4/1 
f 4/5/2 3/4/2 7/6/2 8/7/2 
f 8/8/3 7/9/3 5/10/3 6/11/3
f 6/12/4 2/13/4 4/5/4 8/14/4
f 2/13/5 1/1/5 3/4/5 4/5/5
f 6/11/6 5/10/6 1/1/6 2/13/6
```
box.mtl:
```
# Blender MTL File: 'None'           
# Material Count: 1
               
newmtl Material
Ns 323.999994                 
Ka 1.000000 1.000000 1.000000  
Kd 0.800000 0.800000 0.800000
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000  
Ni 1.450000                     
d 1.000000                    
illum 2            
```

and, here is how to reproduce:

```
>>> mesh = trimesh.load('./output/box.obj')
>>> mesh.export('./output/test.obj')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stone/anaconda3/lib/python3.7/site-packages/trimesh/base.py", line 2554, in export
    **kwargs)
  File "/home/stone/anaconda3/lib/python3.7/site-packages/trimesh/exchange/export.py", line 78, in export_mesh
    export = _mesh_exporters[file_type](mesh, **kwargs)
  File "/home/stone/anaconda3/lib/python3.7/site-packages/trimesh/exchange/obj.py", line 837, in export_obj
    digits=digits))
  File "/home/stone/anaconda3/lib/python3.7/site-packages/trimesh/util.py", line 1151, in array_to_string
    array.dtype.name)
ValueError: ('dtype %s not convertible!', 'object')
```

**Comment by mikedh** [comment]
Thanks for the report and reproducible example!
