### ISSUE TITLE
.show() on Path3D fails with numpy error.

### ISSUE THREAD

**Issue by Skylion007** [mikedh/trimesh#1122]
I wanted to visualize the outline of a convex hull.
To reproduce:
```
scene = trimesh.load(SCENE)
hull = scene.convex_hull
hull.outline().show()
```

This is a on fresh conda install with numpy 1.19.5

Example Traceback:
```
Traceback (most recent call last):
  File "test_script_trimesh_stats.py", line 76, in <module>
    get_scene_stats(filename)
  File "test_script_trimesh_stats.py", line 53, in get_scene_stats
    (hull.outline()).show()
  File "/Users/agokaslan/miniconda/envs/trimesh/lib/python3.8/site-packages/trimesh/path/path.py", line 967, in show
    return scene.show(**kwargs)
  File "/Users/agokaslan/miniconda/envs/trimesh/lib/python3.8/site-packages/trimesh/scene/scene.py", line 1049, in show
    return SceneViewer(self, **kwargs)
  File "/Users/agokaslan/miniconda/envs/trimesh/lib/python3.8/site-packages/trimesh/viewer/windowed.py", line 96, in __init__
    self._initial_camera_transform = scene.camera_transform.copy()
  File "/Users/agokaslan/miniconda/envs/trimesh/lib/python3.8/site-packages/trimesh/scene/scene.py", line 585, in camera_transform
    return self.graph[self.camera.name][0]
  File "/Users/agokaslan/miniconda/envs/trimesh/lib/python3.8/site-packages/trimesh/scene/scene.py", line 644, in camera
    return self.set_camera()
  File "/Users/agokaslan/miniconda/envs/trimesh/lib/python3.8/site-packages/trimesh/scene/scene.py", line 557, in set_camera
    self.bounds_corners,
  File "/Users/agokaslan/miniconda/envs/trimesh/lib/python3.8/site-packages/trimesh/caching.py", line 100, in get_cached
    value = function(*args, **kwargs)
  File "/Users/agokaslan/miniconda/envs/trimesh/lib/python3.8/site-packages/trimesh/scene/scene.py", line 300, in bounds_corners
    corners_geom = {k: bounds_module.corners(v.bounds)
  File "/Users/agokaslan/miniconda/envs/trimesh/lib/python3.8/site-packages/trimesh/scene/scene.py", line 302, in <dictcomp>
    if v.bounds is not None}
  File "/Users/agokaslan/miniconda/envs/trimesh/lib/python3.8/site-packages/trimesh/caching.py", line 100, in get_cached
    value = function(*args, **kwargs)
  File "/Users/agokaslan/miniconda/envs/trimesh/lib/python3.8/site-packages/trimesh/path/path.py", line 345, in bounds
    return np.array([points.min(axis=0),
  File "/Users/agokaslan/miniconda/envs/trimesh/lib/python3.8/site-packages/numpy/core/_methods.py", line 43, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by mikedh** [comment]
So what's happening is the `convex_hull` is a well-constructed mesh, with no "holes," so the `outline` of that is none/null/empty. 

You might take a look at the `convex_hull.section` on a few planes for a non-empty outline curve.

**Comment by Skylion007** [comment]
@mikedh I was looking for a ConvexHull equivalent of https://github.com/mikedh/trimesh/blob/63e35a5652c9525a6a8070271c2bac8f4d13105b/trimesh/primitives.py#L607 is there anyway to get a similar functionality from convex hulls?
