### ISSUE TITLE
Plot a pointcloud

### ISSUE THREAD

**Issue by pvnieo** [mikedh/trimesh#1157]
Hi,

Thanks for the great library.

Is there a way to plot a pointcloud (no faces provided) using `mesh.show()` ? The usual way with 3D surface meshes doesn't work?

Thank you in advance!

Here is the error I'm getting (the shape has 5000 vertices and not 0):
```python
>>> import trimesh
>>> mesh = trimesh.load("1-2.off")
>>> mesh.show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/levi/.local/lib/python3.8/site-packages/trimesh/base.py", line 2433, in show
    return scene.show(**kwargs)
  File "/home/levi/.local/lib/python3.8/site-packages/trimesh/scene/scene.py", line 1089, in show
    return SceneViewer(self, **kwargs)
  File "/home/levi/.local/lib/python3.8/site-packages/trimesh/viewer/windowed.py", line 95, in __init__
    self._initial_camera_transform = scene.camera_transform.copy()
  File "/home/levi/.local/lib/python3.8/site-packages/trimesh/scene/scene.py", line 586, in camera_transform
    return self.graph[self.camera.name][0]
  File "/home/levi/.local/lib/python3.8/site-packages/trimesh/scene/scene.py", line 645, in camera
    return self.set_camera()
  File "/home/levi/.local/lib/python3.8/site-packages/trimesh/scene/scene.py", line 557, in set_camera
    transform = cameras.look_at(
  File "/home/levi/.local/lib/python3.8/site-packages/trimesh/scene/cameras.py", line 324, in look_at
    points_c = rinv.dot(points.T).T
ValueError: shapes (3,3) and (0,) not aligned: 3 (dim 1) != 0 (dim 0)
```

**Comment by pvnieo** [comment]
I solved this By using:
```python
import trimesh
mesh = trimesh.load("1-2.off")
pct = trimesh.PointCloud(mesh.vertices)
trimesh.Scene(pct).show()
```
Is there a way to adjust the size of the displayed points?

**Comment by pvnieo** [comment]
Solved using:
```python
scene.save_image(resolution=(1080, 1080), line_settings= {'point_size': 20})
```
