### ISSUE TITLE
Is there a way to read the face colors of an object uploaded by trimesh API?

### ISSUE THREAD

**Issue by RancidSpring** [mikedh/trimesh#1202]
I am trying to get information about the colors of each face of an object created in Blender. I have a .obj and .mtl (with specified materials) files prepared. Mtl file contains:

`# Blender MTL File: 'None'
# Material Count: 2

newmtl Material.001
Ns 323.999994
Ka 1.000000 1.000000 1.000000
Kd 0.992857 0.000000 0.003671
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.000000
d 1.000000
illum 2

newmtl material_0
Ns 0.000000
Ka 1.000000 1.000000 1.000000
Kd 0.000000 1.000000 0.000000
Ks 1.000000 1.000000 1.000000
Ke 0.000000 0.000000 0.000000
Ni 1.000000
d 1.000000
illum 2`

I tried to load the .obj type file into scene object:
`file_name = 'objects/<MyObj>.obj'
resolver = trimesh.visual.resolvers.FilePathResolver(file_name)
with open(file_name, 'r') as f:
    kwargs = trimesh.exchange.obj.load_obj(f, resolver=resolver)
scene = trimesh.exchange.load.load_kwargs(kwargs)`

But I couldn't find any information about how to get an array of face colors.
I also tried to make a ColorVisuals object myself, but it returns default face_colors if they are not specified as a function argument.
`visuals = trimesh.visual.color.ColorVisuals(list(scene.geometry.items())[1][1])`

I also would be grateful for any information about any way to get an array of face colors of a .obj type object in Python. I use them later in my project to mark an object's special faces in the robotics field to design my grasping algorithm.

**Comment by mikedh** [comment]
Hey, I'd probably do the loading more easily with `mesh = trimesh.load(file_name, force='mesh')`. It may have loaded visuals as texture, which you can approximately convert pretty easily. 

```
In [1]: import trimesh

In [2]: m = trimesh.load('models/machinist.XAML')

In [3]: m
Out[3]: <trimesh.Trimesh(vertices.shape=(3002, 3), faces.shape=(2990, 3))>

In [4]: _ = m.export('models/machinist.obj')

In [5]: r = trimesh.load('models/machinist.obj')

In [6]: r
Out[6]: <trimesh.Trimesh(vertices.shape=(3002, 3), faces.shape=(2990, 3))>

In [7]: r.visual
Out[7]: <trimesh.visual.color.ColorVisuals at 0x7f4dc39d4970>

In [8]: r.visual.kind
Out[8]: 'vertex'

In [9]: r.show()
Out[9]: SceneViewer(width=1800, height=1350)

In [10]: m = trimesh.load('models/fuze.obj')

In [11]: m.visual
Out[11]: <trimesh.visual.texture.TextureVisuals at 0x7f4db9556f70>

In [12]: m.visual = m.visual.to_color()

In [13]: m.visual.kind
Out[13]: 'vertex'

In [14]: m.visual.vertex_colors
Out[14]: 
TrackedArray([[167,   0,  43, 255],
              [157,  43,  42, 255],
              [127, 127, 127, 255],
              ...,
              [164,  14,  59, 255],
              [165,   0,   7, 255],
              [163, 111,   2, 255]], dtype=uint8)

In [15]: m.visual.face_colors
Out[15]: 
TrackedArray([[127, 127, 127, 255],
              [127, 127, 127, 255],
              [127, 127, 127, 255],
              ...,
              [127,  65,  73, 255],
              [146,   0,  44, 255],
              [112,  58,  69, 255]], dtype=uint8)
```

**Comment by RancidSpring** [comment]
Thank you for your answer!

I tried to load my object like this:
`mesh = trimesh.load(file_name, force='mesh')`
`visuals = mesh.visual`
Then I got an error:
<pre><code> concatenating texture: may result in visual artifacts 
failed to combine visuals  
Traceback (most recent call last): 
  File "python3.6/site-packages/trimesh/util.py", line 1436, in concatenate
    [m.visual for m in meshes[1:]])  
  File "python3.6/site-packages/trimesh/visual/texture.py", line 209, in concatenate  
    return concatenate(self, others)  
  File "python3.6/site-packages/trimesh/visual/objects.py", line 80, in concatenate  
    new_mat, new_uv = pack(materials=mats, uvs=uvs)  
  File "python3.6/site-packages/trimesh/visual/material.py", line 420, in pack  
    final, offsets = packing.images(images, power_resize=True)  
  File "python3.6/site-packages/trimesh/path/packing.py", line 429, in images  
    rect = np.array([i.size for i in images])  
  File "python3.6/site-packages/trimesh/path/packing.py", line 429, in <listcomp>  
    rect = np.array([i.size for i in images])  
AttributeError: 'NoneType' object has no attribute 'size'  </code></pre>

I can see that the colors of faces are not loaded in visualization, and the object has default colors. 
However, when I load the object as a Scene by:
<pre><code>
mesh = trimesh.load(file_name)
</code></pre>
the visualization **has all the face colors I am trying to get.**
I tried to access them through the texture:
`visuals = list(mesh.geometry.items())[1][1].visual.to_color().face_colors`
But the output was an error:
<pre><code>
Traceback (most recent call last):
  File "test.py", line 92, in <module>
    visuals = list(mesh.geometry.items())[1][1].visual.to_color().face_colors
  File "python3.6/site-packages/trimesh/visual/color.py", line 170, in face_colors
    return self._get_colors(name='face')
  File "python3.6/site-packages/trimesh/visual/color.py", line 321, in _get_colors
    (count, 1))
  File "<__array_function__ internals>", line 6, in tile
  File "python3.6/site-packages/numpy/lib/shape_base.py", line 1253, in tile
    shape_out = tuple(s*t for s, t in zip(c.shape, tup))
  File "python3.6/site-packages/numpy/lib/shape_base.py", line 1253, in <genexpr>
    shape_out = tuple(s*t for s, t in zip(c.shape, tup))
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
</code></pre>

Maybe there is something wrong with the object? I colored the object in Blender and exported it as a .obj.

Thank you again!

**Comment by mikedh** [comment]
Ah yeah the load issue is a concatenation bug on meshes with a material defined without a texture image. The to-color may be failing because there is a material defined with color but no texture. Can you post or email me the mesh so I can take a look?

**Comment by RancidSpring** [comment]
Of course, here are the .obj and .mtl files I used

вс, 4 апр. 2021 г. в 16:37, Michael Dawson-Haggerty <
***@***.***>:

**Comment by mikedh** [comment]
Looks like GitHub dropped the attachment, can you send it to `mikedh@kerfed.com`?

**Comment by sai-cherukumilli-enview** [comment]
I am having the same issue. 

Here's the code I use to load the mesh - 
```python
temp_output_path = "pickuptruck_shell.obj" # original pickuptruck.3dm was exported via rhino7 after interiors removed
source_mesh = trimesh.load(temp_output_path, force='mesh')
print(source_mesh.visual.kind) # None
print(source_mesh.visual.main_color) # [102 102 102 255]
```

The console output is below:
```

[2021-04-20 10:41:26] DEBUG   (load.py:224) loaded <trimesh.Scene(len(geometry)=11)> using load_obj
[2021-04-20 10:41:26] DEBUG   (constants.py:137) load_mesh executed in 2.5295 seconds.
loaded <trimesh.Scene(len(geometry)=11)> using load_obj
load_mesh executed in 2.5295 seconds.
[2021-04-20 10:41:26] DEBUG   (base.py:2219) apply_transform passed identity matrix
apply_transform passed identity matrix
[2021-04-20 10:41:26] DEBUG   (base.py:2219) apply_transform passed identity matrix
apply_transform passed identity matrix
[2021-04-20 10:41:26] DEBUG   (base.py:2219) apply_transform passed identity matrix
apply_transform passed identity matrix
[2021-04-20 10:41:26] DEBUG   (base.py:2219) apply_transform passed identity matrix
apply_transform passed identity matrix
[2021-04-20 10:41:26] DEBUG   (base.py:2219) apply_transform passed identity matrix
apply_transform passed identity matrix
[2021-04-20 10:41:26] DEBUG   (base.py:2219) apply_transform passed identity matrix
apply_transform passed identity matrix
[2021-04-20 10:41:26] DEBUG   (base.py:2219) apply_transform passed identity matrix
apply_transform passed identity matrix
apply_transform passed identity matrix
[2021-04-20 10:41:26] DEBUG   (base.py:2219) apply_transform passed identity matrix
apply_transform passed identity matrix
[2021-04-20 10:41:26] DEBUG   (base.py:2219) apply_transform passed identity matrix
apply_transform passed identity matrix
[2021-04-20 10:41:26] DEBUG   (base.py:2219) apply_transform passed identity matrix
[2021-04-20 10:41:26] DEBUG   (base.py:2219) apply_transform passed identity matrix
apply_transform passed identity matrix
[2021-04-20 10:41:26] WARNING (texture.py:211) concatenating texture: may result in visual artifacts
concatenating texture: may result in visual artifacts
[2021-04-20 10:41:26] DEBUG   (util.py:1534) failed to combine visuals
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/trimesh/util.py", line 1531, in concatenate
    [m.visual for m in meshes[1:]])
  File "/usr/local/lib/python3.6/dist-packages/trimesh/visual/texture.py", line 213, in concatenate
    return concatenate(self, others)
  File "/usr/local/lib/python3.6/dist-packages/trimesh/visual/objects.py", line 80, in concatenate
    new_mat, new_uv = pack(materials=mats, uvs=uvs)
  File "/usr/local/lib/python3.6/dist-packages/trimesh/visual/material.py", line 432, in pack
    final, offsets = packing.images(images, power_resize=True)
  File "/usr/local/lib/python3.6/dist-packages/trimesh/path/packing.py", line 429, in images
    rect = np.array([i.size for i in images])
  File "/usr/local/lib/python3.6/dist-packages/trimesh/path/packing.py", line 429, in <listcomp>
    rect = np.array([i.size for i in images])
AttributeError: 'NoneType' object has no attribute 'size'
failed to combine visuals
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/trimesh/util.py", line 1531, in concatenate
    [m.visual for m in meshes[1:]])
  File "/usr/local/lib/python3.6/dist-packages/trimesh/visual/texture.py", line 213, in concatenate
    return concatenate(self, others)
  File "/usr/local/lib/python3.6/dist-packages/trimesh/visual/objects.py", line 80, in concatenate
    new_mat, new_uv = pack(materials=mats, uvs=uvs)
  File "/usr/local/lib/python3.6/dist-packages/trimesh/visual/material.py", line 432, in pack
    final, offsets = packing.images(images, power_resize=True)
  File "/usr/local/lib/python3.6/dist-packages/trimesh/path/packing.py", line 429, in images
    rect = np.array([i.size for i in images])
  File "/usr/local/lib/python3.6/dist-packages/trimesh/path/packing.py", line 429, in <listcomp>
    rect = np.array([i.size for i in images])
AttributeError: 'NoneType' object has no attribute 'size'
```

The contents of my zip file are larger than 10 mb. I'm sharing the zip file as a google drive link - 
https://drive.google.com/file/d/1qy92qzGR2iribx1wMZ4YLX6iXmZmf7iW/view?usp=sharing
