### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'faces', also how can I remesh or remove defetcs?

### ISSUE THREAD

**Issue by AggamR** [mikedh/trimesh#1298]
Hello. I'm trying to subdivide a mesh and I'm having this error:
```
PS E:\Memomi\Scripting> py .\meshfix.py
concatenating texture: may result in visual artifacts
Traceback (most recent call last):
  File "E:\Memomi\Scripting\meshfix.py", line 8, in <module>
    exp.export_mesh(newmesh, "new980313745.obj", file_type="obj")
  File "E:\Programs\Python396\lib\site-packages\trimesh\exchange\export.py", line 67, in export_mesh
    faces += len(m.faces)
AttributeError: 'numpy.ndarray' object has no attribute 'faces'
```

My code:
```
import trimesh.exchange.export as exp
import trimesh.remesh
import trimesh


mesh = trimesh.load('980313745.obj', force='mesh')
newmesh = trimesh.remesh.subdivide(mesh.vertices, mesh.faces)
exp.export_mesh(newmesh, "new980313745.obj", file_type="obj")
```

Also, is there a way to just remesh or remove defects from a mesh?

**Comment by mikedh** [comment]
Hey, `trimesh.remesh.subdivide` doesn't return a mesh object, the engineering reason being to make functions have clear inputs and outputs. 

```
In [8]: trimesh.remesh.subdivide?
Signature:
trimesh.remesh.subdivide(
    vertices,
    faces,
    face_index=None,
    vertex_attributes=None,
)
Docstring:
Subdivide a mesh into smaller triangles.

Note that if `face_index` is passed, only those
faces will be subdivided and their neighbors won't
be modified making the mesh no longer "watertight."

Parameters
------------
vertices : (n, 3) float
  Vertices in space
faces : (m, 3) int
  Indexes of vertices which make up triangular faces
face_index : faces to subdivide.
  if None: all faces of mesh will be subdivided
  if (n,) int array of indices: only specified faces
vertex_attributes : dict
  Contains (n, d) attribute data

Returns
----------
new_vertices : (q, 3) float
  Vertices in space
new_faces : (p, 3) int
  Remeshed faces
```

I think you want to call `mesh.subdivide()` which will apply the subdivision in-place to the current mesh.

```

mesh = trimesh.load('980313745.obj', force='mesh')
mesh.subdivide()
mesh.export("new980313745.obj")
```
