### ISSUE TITLE
Trimesh won't export as gltf

### ISSUE THREAD

**Issue by Tzanker** [mikedh/trimesh#1304]
Hi I am trying to export a scene as a gltf file and i keep getting the error below. All I do is load a textured object and export it:
```
import trimesh
mesh = trimesh.load("odm_textured_model_geo.obj")
mesh.export(file_obj="output/landslide.gltf")
```

Error message:

```Traceback (most recent call last):
  File "C:/Users/teva/Documents/GitHub/firebird3d/modelTesting.py", line 18, in <module>
    mesh.export(file_obj="output/landslide.gltf")
  File "C:\Users\teva\Miniconda3\envs\firebird3d_3.8\lib\site-packages\trimesh\scene\scene.py", line 836, in export
    return export.export_scene(
  File "C:\Users\teva\Miniconda3\envs\firebird3d_3.8\lib\site-packages\trimesh\exchange\export.py", line 250, in export_scene
    util.write_encoded(f, data)
  File "C:\Users\teva\Miniconda3\envs\firebird3d_3.8\lib\site-packages\trimesh\util.py", line 2116, in write_encoded
    file_obj.write(stuff)
TypeError: a bytes-like object is required, not 'dict'

Process finished with exit code 1
```

**Comment by mikedh** [comment]
Thanks for the report! Not sure what's going on here, it may be hitting a code path that isn't covered in tests. Would you be able to share the failing model? mikedh@kerfed.com 

FWIW a similar example works for me:

```
In [1]: import trimesh
m =-
In [2]: m = trimesh.load('models/fuze.obj', force='scene')

In [3]: m
Out[3]: <trimesh.Scene(len(geometry)=1)>

In [4]: e = m.export(file_type='glb')

In [5]: len(e)
Out[5]: 114008

```

**Comment by 987123879113** [comment]
I ran into this same issue the other day and finally got around to trying to work it out.

The issue stems from using `file_obj`. When `file_obj` is specified, it wants to create a single file object using that filename. Using `export` to create a gltf file calls `export_gltf` which returns a dict where the keys are the output filenames and the values are the data for each file: 
https://github.com/mikedh/trimesh/blob/e5c13c2dabd8d012b1eca8ec11884b2e51f098e8/trimesh/exchange/gltf.py#L85-L88

```python
>>> data = scene.export(file_type="gltf")
>>> print(data.keys())
dict_keys(['gltf_buffer_0.bin', 'gltf_buffer_1.bin', 'gltf_buffer_2.bin', 'gltf_buffer_3.bin', 'gltf_buffer_4.bin', 'gltf_buffer_5.bin', 'gltf_buffer_6.bin', 'gltf_buffer_7.bin', 'gltf_buffer_8.bin', 'gltf_buffer_9.bin', 'gltf_buffer_10.bin', 'gltf_buffer_11.bin', 'gltf_buffer_12.bin', 'gltf_buffer_13.bin', 'gltf_buffer_14.bin', 'gltf_buffer_15.bin', 'gltf_buffer_16.bin', 'gltf_buffer_17.bin', 'gltf_buffer_18.bin', 'gltf_buffer_19.bin', 'gltf_buffer_20.bin', 'gltf_buffer_21.bin', 'gltf_buffer_22.bin', 'gltf_buffer_23.bin', 'gltf_buffer_24.bin', 'gltf_buffer_25.bin', 'gltf_buffer_26.bin', 'gltf_buffer_27.bin', 'gltf_buffer_28.bin', 'gltf_buffer_29.bin', 'gltf_buffer_30.bin', 'gltf_buffer_31.bin', 'gltf_buffer_32.bin', 'gltf_buffer_33.bin', 'gltf_buffer_34.bin', 'gltf_buffer_35.bin', 'gltf_buffer_36.bin', 'gltf_buffer_37.bin', 'gltf_buffer_38.bin', 'gltf_buffer_39.bin', 'gltf_buffer_40.bin', 'gltf_buffer_41.bin', 'gltf_buffer_42.bin', 'gltf_buffer_43.bin', 'gltf_buffer_44.bin', 'gltf_buffer_45.bin', 'gltf_buffer_46.bin', 'gltf_buffer_47.bin', 'gltf_buffer_48.bin', 'gltf_buffer_49.bin', 'gltf_buffer_50.bin', 'gltf_buffer_51.bin', 'gltf_buffer_52.bin', 'gltf_buffer_53.bin', 'gltf_buffer_54.bin', 'gltf_buffer_55.bin', 'gltf_buffer_56.bin', 'gltf_buffer_57.bin', 'gltf_buffer_58.bin', 'gltf_buffer_59.bin', 'gltf_buffer_60.bin', 'gltf_buffer_61.bin', 'gltf_buffer_62.bin', 'gltf_buffer_63.bin', 'gltf_buffer_64.bin', 'gltf_buffer_65.bin', 'gltf_buffer_66.bin', 'gltf_buffer_67.bin', 'gltf_buffer_68.bin', 'gltf_buffer_69.bin', 'gltf_buffer_70.bin', 'gltf_buffer_71.bin', 'gltf_buffer_72.bin', 'gltf_buffer_73.bin', 'gltf_buffer_74.bin', 'gltf_buffer_75.bin', 'gltf_buffer_76.bin', 'gltf_buffer_77.bin', 'model.gltf'])
```

Because a gltf is supposed to be exporting to multiple files, I don't think it's possible to actually use `file_obj` to export a gltf file. For gltfs you'll need to do something like this:
```python
data = scene.export(file_type="gltf")
for k in data:
    open(k, "wb").write(data[k])
```

Hope this helps at all.

**Comment by mikedh** [comment]
Oh I misread the original issue; yeah `gltf` exports return a dict, as the `gltf` format is multiple files and we can't write to a single file object or location, and @987123879113's solution is the way it was intended to be consumed. Thanks for the report!

**Comment by iportolesrb** [comment]
Hi,

I have the same issue, how could I do it to export to a .gltf file then?
