### ISSUE TITLE
Make "exe" with pyinstaller - dont works

### ISSUE THREAD

**Issue by TommyK82** [mikedh/trimesh#131]
Hello,

I opened  this toppic  and closed  it quick afterwards, because I thought I found  a workaround, but  unfortunately I didn't. Therefore I reopened it.

I tried to transform a trimesh script   into an "exe" file with pyinstaller, but this works not  with trimesh, even at a very simple script.   It looks like that there are some issues between trimesh and scipy, which causes the error. Using only scipy works, but not trimesh.

Any hints are appreciated

P.S.:  here how this  issue was solved with scipy: https://stackoverflow.com/questions/35060523/how-to-use-pyinstaller-with-hidden-imports-for-scipy-optimize-leastsq

This is the script:

```
import trimesh
print("TEST")

```

This is the error, when I execute the exe:

```
C:\...\test2>test2.exe
Traceback (most recent call last):
  File "test2.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files (x86)\python36-32\lib\site-packages\PyInstaller\loader\
pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\trimesh\__init__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files (x86)\python36-32\lib\site-packages\PyInstaller\loader\
pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\trimesh\base.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files (x86)\python36-32\lib\site-packages\PyInstaller\loader\
pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\trimesh\graph.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files (x86)\python36-32\lib\site-packages\PyInstaller\loader\
pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\trimesh\grouping.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files (x86)\python36-32\lib\site-packages\PyInstaller\loader\
pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\scipy\spatial\__init__.py", line 95, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "c:\program files (x86)\python36-32\lib\site-packages\PyInstaller\loader\
pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
  File "qhull.pyx", line 230, in init scipy.spatial.qhull
AttributeError: type object 'scipy.spatial.qhull._Qhull' has no attribute '__red
uce_cython__'
[6848] Failed to execute script test2
```

**Comment by mikedh** [comment]
Hey Tommy- does this work with your pipeline:

```
from scipy import spatial
print('testing')
```

**Comment by TommyK82** [comment]
Hi Mike,

no it doesn't work,  so it probably  not a trimesh issue (so I will close the issue).  Sry for bothering you ...

Any hint what the reason could be?

Many Thanks


here my error:
```
C:\...\test2>test2.exe
Traceback (most recent call last):
  File "test2.py", line 1, in <module>
  File "c:\program files (x86)\python36-32\lib\site-packages\PyInstaller\loader\
pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\scipy\spatial\__init__.py", line 95, in <module>
  File "c:\program files (x86)\python36-32\lib\site-packages\PyInstaller\loader\
pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
  File "messagestream.pxd", line 5, in init scipy.spatial.qhull
ModuleNotFoundError: No module named 'scipy._lib.messagestream'
[5572] Failed to execute script test2
```
