### ISSUE TITLE
RuntimeError: generator raised StopIteration when calling `is_filled` method

### ISSUE THREAD

**Issue by Co1lin** [mikedh/trimesh#1315]
`is_filled` method works fine for some points, but it crashes for some other points.

The error below indicates that for some inputs, argument `ordered_indices` for function `sorted_rle_gather_1d` in `runlength.py` is empty.
```python
Traceback (most recent call last):
  File "/home/aidrive1/miniconda3/envs/dr/lib/python3.8/site-packages/trimesh/voxel/runlength.py", line 378, in sorted_rle_gather_1d
    index = next(index_iter)
StopIteration
```

Details:

```python
In [5]: voxel2_surface
Out[5]: <trimesh.VoxelGrid(18, 18, 18)>

In [6]: v1_points
Out[6]: 
array([[ 1.15973   , -0.25133982, -0.0182148 ],
       [ 1.15973   , -0.18839218, -0.0182148 ],
       [ 1.15973   , -0.25133982,  0.04473284],
       ...,
       [ 1.852154  , -0.37723509,  0.42241865],
       [ 1.852154  , -0.37723509,  0.48536629],
       [ 1.852154  , -0.37723509,  0.54831393]])

In [7]: voxel2_surface.is_filled([[0.2,0.2,0.2]])
Out[7]: array([False])

In [8]: voxel2_surface.is_filled([v1_points[0]])
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/aidrive1/miniconda3/envs/dr/lib/python3.8/site-packages/trimesh/voxel/runlength.py", line 378, in sorted_rle_gather_1d
    index = next(index_iter)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aidrive1/miniconda3/envs/dr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/aidrive1/miniconda3/envs/dr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/data/colin/DRNet/net_utils/eval_det.py", line 350, in eval_det_cls_wrapper_w_mesh
    (rec, prec, ap), (rec_mesh, prec_mesh, ap_mesh) = eval_det_cls_w_mesh(pred, gt, ovthresh, use_07_metric, get_iou_func, get_iou_mesh)
  File "/data/colin/DRNet/net_utils/eval_det.py", line 211, in eval_det_cls_w_mesh
    iou_mesh = get_iou_main(get_iou_mesh, (mesh_pred, MESH_GT[j]))
  File "/data/colin/DRNet/net_utils/eval_det.py", line 94, in get_iou_main
    return get_iou_func(*args)
  File "/data/colin/DRNet/net_utils/eval_det.py", line 49, in compute_mesh_iou
    v1_in_v2 = sum(voxel2_surface.is_filled(v1_points) + voxel2_internal.is_filled(v1_points))
  File "/home/aidrive1/miniconda3/envs/dr/lib/python3.8/site-packages/trimesh/voxel/base.py", line 208, in is_filled
    is_filled[in_range] = self.encoding.gather_nd(indices[in_range])
  File "/home/aidrive1/miniconda3/envs/dr/lib/python3.8/site-packages/trimesh/voxel/encoding.py", line 697, in gather_nd
    return self._data.gather_nd(self._to_base_indices(indices))
  File "/home/aidrive1/miniconda3/envs/dr/lib/python3.8/site-packages/trimesh/voxel/encoding.py", line 697, in gather_nd
    return self._data.gather_nd(self._to_base_indices(indices))
  File "/home/aidrive1/miniconda3/envs/dr/lib/python3.8/site-packages/trimesh/voxel/encoding.py", line 524, in gather_nd
    return self.gather(indices)
  File "/home/aidrive1/miniconda3/envs/dr/lib/python3.8/site-packages/trimesh/voxel/encoding.py", line 520, in gather
    return rl.rle_gather_1d(self._data, indices, dtype=self._dtype)
  File "/home/aidrive1/miniconda3/envs/dr/lib/python3.8/site-packages/trimesh/voxel/runlength.py", line 495, in rle_gather_1d
    return rle_gatherer_1d(indices)(rle_data, dtype=dtype)
  File "/home/aidrive1/miniconda3/envs/dr/lib/python3.8/site-packages/trimesh/voxel/runlength.py", line 353, in f
    result[order] = tuple(sorted_gather_fn(data, ordered_indices))
RuntimeError: generator raised StopIteration
"""

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
/data/colin/DRNet/net_utils/eval_det.py in eval_det_multiprocessing_w_mesh(pred_all, gt_all, ovthresh, use_07_metric, get_iou_func, get_iou_mesh)
    397         p = Pool(processes=num_processes)
--> 398         ret_values = p.map(eval_det_cls_wrapper_w_mesh,
    399                            [(pred[classname], gt[classname], ovthresh, use_07_metric, get_iou_func, get_iou_mesh) for classname in

~/miniconda3/envs/dr/lib/python3.8/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    363         '''
--> 364         return self._map_async(func, iterable, mapstar, chunksize).get()
    365 

~/miniconda3/envs/dr/lib/python3.8/multiprocessing/pool.py in get(self, timeout)
    770         else:
--> 771             raise self._value
    772 

RuntimeError: generator raised StopIteration

During handling of the above exception, another exception occurred:

StopIteration                             Traceback (most recent call last)
~/miniconda3/envs/dr/lib/python3.8/site-packages/trimesh/voxel/runlength.py in sorted_rle_gather_1d(rle_data, ordered_indices)
    377     index_iter = iter(ordered_indices)
--> 378     index = next(index_iter)
    379     start = 0

StopIteration: 

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
/data/colin/DRNet/net_utils/eval_det.py in <module>
----> 1 voxel2_surface.is_filled([v1_points[0]])

~/miniconda3/envs/dr/lib/python3.8/site-packages/trimesh/voxel/base.py in is_filled(self, point)
    206 
    207         is_filled = np.zeros_like(in_range)
--> 208         is_filled[in_range] = self.encoding.gather_nd(indices[in_range])
    209         return is_filled
    210 

~/miniconda3/envs/dr/lib/python3.8/site-packages/trimesh/voxel/encoding.py in gather_nd(self, indices)
    695 
    696     def gather_nd(self, indices):
--> 697         return self._data.gather_nd(self._to_base_indices(indices))
    698 
    699     def get_value(self, index):

~/miniconda3/envs/dr/lib/python3.8/site-packages/trimesh/voxel/encoding.py in gather_nd(self, indices)
    695 
    696     def gather_nd(self, indices):
--> 697         return self._data.gather_nd(self._to_base_indices(indices))
    698 
    699     def get_value(self, index):

~/miniconda3/envs/dr/lib/python3.8/site-packages/trimesh/voxel/encoding.py in gather_nd(self, indices)
    522     def gather_nd(self, indices):
    523         indices = np.squeeze(indices, axis=-1)
--> 524         return self.gather(indices)
    525 
    526     def sorted_gather(self, ordered_indices):

~/miniconda3/envs/dr/lib/python3.8/site-packages/trimesh/voxel/encoding.py in gather(self, indices)
    518 
    519     def gather(self, indices):
--> 520         return rl.rle_gather_1d(self._data, indices, dtype=self._dtype)
    521 
    522     def gather_nd(self, indices):

~/miniconda3/envs/dr/lib/python3.8/site-packages/trimesh/voxel/runlength.py in rle_gather_1d(rle_data, indices, dtype)
    493     rle_data
    494     """
--> 495     return rle_gatherer_1d(indices)(rle_data, dtype=dtype)
    496 
    497 

~/miniconda3/envs/dr/lib/python3.8/site-packages/trimesh/voxel/runlength.py in f(data, dtype)
    351     def f(data, dtype=None):
    352         result = np.empty(len(order), dtype=dtype or getattr(data, 'dtype', None))
--> 353         result[order] = tuple(sorted_gather_fn(data, ordered_indices))
    354         return result
    355 

RuntimeError: generator raised StopIteration
```

**Comment by mikedh** [comment]
Fixed by your PR, thanks!
