### ISSUE TITLE
Getting error trying to run projection function

### ISSUE THREAD

**Issue by uttaparsa** [mikedh/trimesh#1439]
Hello,
I am using version 3.9.36.
When I try to execute projected function on my mesh I get following error:

```
Traceback (most recent call last):
  File "/home/parsa/Documents/test/python_workshop/cts/trimesh_center_in_pyvista.py", line 8, in <module>
    projection = mesh.projected(normal=[0,0,1])
  File "/home/parsa/Documents/test/python_workshop/venv/lib/python3.9/site-packages/trimesh/base.py", line 2539, in projected
    return load_path(projected(mesh=self, normal=normal, **kwargs))
  File "/home/parsa/Documents/test/python_workshop/venv/lib/python3.9/site-packages/trimesh/path/exchange/load.py", line 62, in load_path
    kwargs.update(misc.lines_to_path(file_obj))
  File "/home/parsa/Documents/test/python_workshop/venv/lib/python3.9/site-packages/trimesh/path/exchange/misc.py", line 56, in lines_to_path
    lines = np.asanyarray(lines, dtype=np.float64)
TypeError: float() argument must be a string or a number, not 'Polygon'
```

my code is:

```
import trimesh
import numpy as np


mesh = trimesh.load_mesh('/home/parsa/Documents/test/python_workshop/cts/703-fixed.ply')


projection = mesh.projected(normal=[0,0,1])

```

Thanks!

**Comment by mikedh** [comment]
That's weird! Can you provide the mesh, my email is mikedh@kerfed.com
