### ISSUE TITLE
slice_plane with cap=True does not return watertight mesh

### ISSUE THREAD

**Issue by rschneider1998** [mikedh/trimesh#1454]
I am using slice_plane to split a mesh along the three main axis. The original is watertight, after slicing it is not. The image below is the return of trimesh.repair.broken_faces(m,color=[255,0,0,255])

<img width="850" alt="image" src="https://user-images.githubusercontent.com/97413065/148703870-a475c5c4-c37e-4154-a29f-b6a9ca78dfa4.png">

Code snippet (x axis) - The try statement is used because at the beginning, slice_plane errors "origin mesh is not watertight", even if it is watertight according to mesh.is_watertight.:
`def slice_in_x(mesh,cuts = 5,display=False):
    """
    Slice a mesh in equal parts along the x-axis (transformation along the axis of a oriented bounding box required
    previously)
    :param mesh: mesh object (or partitial mesh; has to be oriented along the axis of a oriented bounding box)
    :param cuts: number of cuts along this axis (results in cuts + 1 partitial mesh)
    :param display: Boolean if the partitial mesh should be displayed (false in default)
    :return: array of mesh objects (submeshes of all cuts)
    """
    #Compute oriented bounding box, get dimensions and reference points (min and max point of each axis)
    bb = mesh.bounding_box_oriented
    bnds = bb.bounds
    minbounds = np.min(bnds, axis=0)
    maxbounds = np.max(bnds, axis=0)
    dimensions = maxbounds-minbounds

    #prepare storage for position of last slice, to define the lower boader of the two cuts
    x_lastaxisvalue = minbounds[0]
    #iterate through all cuts (resulting in cuts + 1 submesh)
    for i in range (0, cuts+1):
        #computing upper boarder/plane
        try:
            submesh = mesh.slice_plane([minbounds[0]+(dimensions[0]/(cuts+1))*(i+1),0,0],[-1,0,0],cap=True)
        except:
            submesh = mesh.slice_plane([minbounds[0] + (dimensions[0] / (cuts + 1)) * (i + 1), 0, 0], [-1, 0, 0],
                                       cap=False)
        #computing lower boarder/plane
        try:
            submesh = submesh.slice_plane([x_lastaxisvalue, 0, 0],[1, 0, 0],cap=True)
        except:
            submesh = submesh.slice_plane([x_lastaxisvalue, 0, 0], [1, 0, 0], cap=False)
        #store the actual upper boarder for use as lower boarder in the next iteration
        x_lastaxisvalue = minbounds[0]+dimensions[0]/(cuts+1)*(i+1)
        if i == 0:
            #create array to save the results
            res = np.array(submesh,dtype=object)
        else:
            # append mesh objects to result-array
            res = np.append(res,submesh)
        if display and not submesh.is_empty:
            #display submesh if existent and wanted by the user
            submesh.show()
    return res #return resulting array of mesh objects`

**Comment by rschneider1998** [comment]
First computation with prove of watertightness:

`#computing upper boarder/plane
        print(mesh.is_watertight)
        submesh = mesh.slice_plane([minbounds[0]+(dimensions[0]/(cuts+1))*(i+1),0,0],[-1,0,0],cap=True)
        #computing lower boarder/plane
        print(submesh.is_watertight)
        submesh = submesh.slice_plane([x_lastaxisvalue, 0, 0],[1, 0, 0],cap=True)`

Error:
`True
False
Traceback (most recent call last):
  File "D:\Dokumente\Dokumente_sync\~\main.py", line 338, in <module>
    test = slice_axis(mesh, cuts=[2,2,2])
  File "D:\Dokumente\Dokumente_sync\~\main.py", line 320, in slice_axis
    s_x = slice_in_x(mesh,cuts[0]) #compute in x
  File "D:\Dokumente\Dokumente_sync\~r\main.py", line 202, in slice_in_x
    submesh = submesh.slice_plane([x_lastaxisvalue, 0, 0],[1, 0, 0],cap=True)
  File "C:\Users\User\.conda\envs\~\lib\site-packages\trimesh\base.py", line 2189, in slice_plane
    new_mesh = intersections.slice_mesh_plane(
  File "C:\Users\User\.conda\envs\~\lib\site-packages\trimesh\intersections.py", line 729, in slice_mesh_plane
    raise ValueError('Input mesh must be watertight to cap slice')
ValueError: Input mesh must be watertight to cap slice`

I Would be very greatful for an idea how to solve this problem, i need these meshes as watertight ones.
