### ISSUE TITLE
Contains_points exception

### ISSUE THREAD

**Issue by robbederks** [mikedh/trimesh#153]
Hi,

I am trying to use trimesh to convert an STL object to a boolean 3D array where the points represent if it is in- or outside the object.

I am using following script:
```
import trimesh

trimesh.util.attach_to_log()

# Load 3D object
mesh = trimesh.load("teapot.stl")

# Get axis bounds
corners = trimesh.bounds.corners(mesh.bounding_box.bounds)
xMin = int(corners[0][0])
xMax = int(corners[1][0])
yMin = int(corners[0][1])
yMax = int(corners[2][1])
zMin = int(corners[0][2])
zMax = int(corners[4][2])

# Calculate if points are inside or outside object
results = []
for x in range(xMin, xMax):
    for y in range(yMin, yMax):
        points = []
        for z in range(zMin, zMax):
            points.append([x, y, z])
        results.append(mesh.ray.contains_points(points))
        print('Calculated for x = ' + str(x) + ' y = ' + str(y))
```

However, when I run it, I get following exception after a few iterations:
```
Traceback (most recent call last):
  File "path_to_local_file/test.py", line 24, in <module>
    results.append(mesh.ray.contains_points(points))
  File "c:\Python36\Lib\site-packages\trimesh\ray\ray_triangle.py", line 134, in contains_points
    return contains_points(self, points)
  File "c:\Python36\Lib\site-packages\trimesh\ray\ray_util.py", line 59, in contains_points
    (ray_directions, -ray_directions)))[1]
  File "c:\Python36\Lib\site-packages\trimesh\ray\ray_triangle.py", line 92, in intersects_location
    **kwargs)
  File "c:\Python36\Lib\site-packages\trimesh\ray\ray_triangle.py", line 60, in intersects_id
    index_ray)))[0]
  File "c:\Python36\Lib\site-packages\trimesh\grouping.py", line 264, in unique_rows
    hashes = hashable_rows(data, digits=digits)
  File "c:\Python36\Lib\site-packages\trimesh\grouping.py", line 107, in hashable_rows
    if np.abs(as_int).max() < 2**(precision - 1):
  File "c:\Python36\Lib\site-packages\numpy\core\_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
builtins.ValueError: zero-size array to reduction operation maximum which has no identity
```

I have also tried it with a fresh install of Python 3.6 and 2.7, without any luck. It also happens with every STL file I use. Attached is the STL file I used in this test.
[teapot.zip](https://github.com/mikedh/trimesh/files/1920024/teapot.zip)

**Comment by mikedh** [comment]
Fix and test in https://github.com/mikedh/trimesh/commit/acc84fe802b74c1003a1c9bbdada9575a151580e

BTW some of the convenience functions on bounding boxes can be good for stuff like this:
```
points = mesh.bounding_box.sample_grid(step=2.0)
results = mesh.ray.contains_points(points)
```
Also, that mesh isn't watertight, so any "inside/outside" query isn't well defined. The implementation in trimesh on that particular mesh will likely return "okay- ish" results, but may be noisy and/or unreliable. 

Thanks for the report!

**Comment by robbederks** [comment]
Thank you for the quick fix!

I didn't check the watertightness of the object, because I am using it on another object. This was just a placeholder with the same issue I encountered.
