### ISSUE TITLE
When changing to a larger dtype, its size must be a divisor of the total size in bytes of the last axis of the array.

### ISSUE THREAD

**Issue by caiyongqi** [mikedh/trimesh#1605]
`
from pytorch3d.ops import sample_points_from_meshes

trg_mesh = Meshes(verts=[verts], faces=[faces_idx])

sampled_trg_vertices = sample_points_from_meshes(trg_mesh, num_samples=4000).float()

sampled_trg_vertices = sampled_trg_vertices.cpu().numpy()

trimesh.Trimesh(vertices=sampled_trg_vertices).export('sampled_trg.obj')
`
Traceback (most recent call last):
  File "", in <module>trimesh.Trimesh(vertices=sampled_trg_vertices).export('sampled_trg.obj')
  File "python3.9/site-packages/trimesh/base.py", line 192, in __init__
    self.process(validate=validate, **kwargs)
  File "python3.9/site-packages/trimesh/base.py", line 228, in process
    self.merge_vertices(**kwargs)
  File "python3.9/site-packages/trimesh/base.py", line 1117, in merge_vertices
    grouping.merge_vertices(self, **kwargs)
  File "python3.9/site-packages/trimesh/grouping.py", line 91, in merge_vertices
    u, i = unique_rows(stacked[referenced])
  File "python3.9/site-packages/trimesh/grouping.py", line 426, in unique_rows
    rows = hashable_rows(data, digits=digits)
  File "python3.9/site-packages/trimesh/grouping.py", line 202, in hashable_rows
    hashable = np.ascontiguousarray(as_int).view(dtype).reshape(-1)
ValueError: When changing to a larger dtype, its size must be a divisor of the total size in bytes of the last axis of the array.

Process finished with exit code 1

**Comment by YounkHo** [comment]
Hi, I met the same problem, did you solve it?
