### ISSUE TITLE
Error loading STL file -- ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by stolarczyk** [mikedh/trimesh#1720]
I'm getting the error pasted below when loading an STL file that seems not to be corrupted and can be loaded with other software.

File to reproduce the error: [fuji_obj.stl.zip](https://github.com/mikedh/trimesh/files/9812554/fuji_obj.stl.zip)

Code to reproduce the error:

```python
tmesh = trimesh.load(fp, force="mesh")
```
Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/trimesh/exchange/stl.py", line 47, in load_stl
    return load_stl_binary(file_obj)
  File "/usr/local/lib/python3.9/site-packages/trimesh/exchange/stl.py", line 116, in load_stl_binary
    raise HeaderError(
trimesh.exchange.stl.HeaderError: Binary STL has incorrect length in header: 55866 vs [110250586]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/usr/local/lib/python3.9/site-packages/prefect/utilities/executors.py", line 468, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/nih_3d_workflows/utils.py", line 59, in gen_trimesh
    return _gen_trimesh(fp)
  File "/usr/local/lib/python3.9/site-packages/nih_3d_workflows/utils.py", line 49, in _gen_trimesh
    tmesh = trimesh.load(fp.as_posix(), force="mesh")
  File "/usr/local/lib/python3.9/site-packages/trimesh/exchange/load.py", line 127, in load
    loaded = load_mesh(file_obj,
  File "/usr/local/lib/python3.9/site-packages/trimesh/constants.py", line 153, in timed
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/trimesh/exchange/load.py", line 209, in load_mesh
    results = mesh_loaders[file_type](file_obj,
  File "/usr/local/lib/python3.9/site-packages/trimesh/exchange/stl.py", line 54, in load_stl
    return load_stl_ascii(file_obj)
  File "/usr/local/lib/python3.9/site-packages/trimesh/exchange/stl.py", line 171, in load_stl_ascii
    header, text = stripped[1].split('\n', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by mikedh** [comment]
This was because the name for a solid in that file includes the word `solid` haha. I pushed some different logic for ASCII STL files but would like to test a bit more before merging.

**Comment by stolarczyk** [comment]
thanks for the update @mikedh. Looking forward to the release!
