### ISSUE TITLE
GLException: No GL context; create a Window first

### ISSUE THREAD

**Issue by yw5aj** [mikedh/trimesh#173]
Hi Mike,

I ran into the same issue with someone else here (https://stackoverflow.com/questions/50545979/glexception-no-gl-context-create-a-window-first):

I also just did:

```
import trimesh

mesh = trimesh.load('cylinder.stl')  # The same file in models/cylinder.stl
mesh.show()
```

And it reports:

```
runfile('X:/temp/trimesh/test.py', wdir='X:/temp/trimesh')
Traceback (most recent call last):

  File "<ipython-input-8-ea54e6a06ddb>", line 1, in <module>
    runfile('X:/temp/trimesh/test.py', wdir='X:/temp/trimesh')

  File "C:\Users\shwang\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\shwang\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "X:/temp/trimesh/test.py", line 4, in <module>
    mesh.show()

  File "C:\Users\shwang\AppData\Local\Continuum\anaconda3\lib\site-packages\trimesh\base.py", line 1911, in show
    scene.show(**kwargs)

  File "C:\Users\shwang\AppData\Local\Continuum\anaconda3\lib\site-packages\trimesh\scene\scene.py", line 635, in show
    SceneViewer(self, **kwargs)

  File "C:\Users\shwang\AppData\Local\Continuum\anaconda3\lib\site-packages\trimesh\scene\viewer.py", line 36, in __init__
    self.reset_view(flags=flags)

  File "C:\Users\shwang\AppData\Local\Continuum\anaconda3\lib\site-packages\trimesh\scene\viewer.py", line 150, in reset_view
    self.update_flags()

  File "C:\Users\shwang\AppData\Local\Continuum\anaconda3\lib\site-packages\trimesh\scene\viewer.py", line 210, in update_flags
    gl.glPolygonMode(gl.GL_FRONT_AND_BACK, gl.GL_FILL)

  File "C:\Users\shwang\AppData\Local\Continuum\anaconda3\lib\site-packages\pyglet\gl\lib.py", line 100, in errcheck
    raise GLException('No GL context; create a Window first')

GLException: No GL context; create a Window first
```

Could you please help me to see whether you have any thoughts?

Shawn

**Comment by mikedh** [comment]
Interesting, some of that traceback is exec/spyder: what happens if you run the same file with just bare python from a terminal?

I wonder if some versions of pyglet are OK with having GL args called without a window and some are not. There's no reason we should need to do that anyway, so I moved the GL init stuff after window creation in https://github.com/mikedh/trimesh/commit/bb8650b5edae84dc14c5b1d2aab3b3670d3a9fdb, after that builds let me know if it helps (`pip install --upgrade trimesh`). 

What version of python and pyglet are you on?

**Comment by yw5aj** [comment]
Thank you Mike!

I forgot to run it before the update in a bare terminal (oops... sorry) and just directly upgraded it with `pip install --upgrade trimesh --no-deps` (because I'm using Windows 10 64 bit). After upgrading, if I just run a bare terminal it would show perfect!

However, in spyder after I run `mesh.show()`, nothing happened at all. I guess it would not be urgent to fix because I have the terminal working!

My pyglet version is 1.3.1, and Python version is 3.6 64 bit.

**Comment by mikedh** [comment]
Ahh, this is related to the ipython notebook detection: since spyder uses ZMQshell trimesh thinks it is in a notebook and is automatically using the ipython/jupyter notebook viewer. I'll try to improve that detection function, but in the meantime you can force it to use pyglet by:

`m.show(viewer='gl')`

**Comment by yw5aj** [comment]
Thank you again Mike for the prompt response.

I used the following code in spyder:

```
import trimesh

mesh = trimesh.load('cylinder.stl')
mesh.show(viewer='gl')
```

And it showed:

```
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 6.2.1 -- An enhanced Interactive Python.

runfile('X:/temp/trimesh/test.py', wdir='X:/temp/trimesh')
Traceback (most recent call last):

  File "<ipython-input-1-ea54e6a06ddb>", line 1, in <module>
    runfile('X:/temp/trimesh/test.py', wdir='X:/temp/trimesh')

  File "C:\Users\shwang\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\shwang\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "X:/temp/trimesh/test.py", line 4, in <module>
    mesh.show(viewer='gl')

  File "C:\Users\shwang\AppData\Local\Continuum\anaconda3\lib\site-packages\trimesh\base.py", line 2015, in show
    return scene.show(**kwargs)

  File "C:\Users\shwang\AppData\Local\Continuum\anaconda3\lib\site-packages\trimesh\scene\scene.py", line 696, in show
    return SceneViewer(self, **kwargs)

  File "C:\Users\shwang\AppData\Local\Continuum\anaconda3\lib\site-packages\trimesh\scene\viewer.py", line 43, in __init__
    height=height)

  File "C:\Users\shwang\AppData\Local\Continuum\anaconda3\lib\site-packages\pyglet\window\__init__.py", line 504, in __init__
    screen = display.get_default_screen()

  File "C:\Users\shwang\AppData\Local\Continuum\anaconda3\lib\site-packages\pyglet\canvas\base.py", line 73, in get_default_screen
    return self.get_screens()[0]

  File "C:\Users\shwang\AppData\Local\Continuum\anaconda3\lib\site-packages\pyglet\canvas\base.py", line 65, in get_screens
    raise NotImplementedError('abstract')

NotImplementedError: abstract
```

**Comment by mikedh** [comment]
No worries.  After you opened this, I was playing around with spyder, and the behavior of the viewer was indeed extremely screwy, probably because they are doing all sorts of `exec`'s and wrapping and whatnot. I'll see if I can get pyglet and spyder to play nicely with each other.

**Comment by mikedh** [comment]
I believe this is fixed in https://github.com/mikedh/trimesh/commit/2b377ec5504c6f25a98be3bc79f630b145ee48f1
