### ISSUE TITLE
AttributeError: 'SceneViewer' object has no attribute 'ubo'

### ISSUE THREAD

**Issue by kappa95** [mikedh/trimesh#1741]
Dear community,
I am trying to use the library on Python 3.8.12 with Ubuntu 18.04. 
Everytime I am trying to show a mesh with: `mesh.show()` I got the following errors:

```python
Traceback (most recent call last):
  File "/home/kappa95/Documenti/RobotAssisted-AdditiveManufacturing/playing_STL/Trimeshtest.py", line 18, in <module>
    mesh.show()
  File "/home/kappa95/Documenti/RobotAssisted-AdditiveManufacturing/venv/lib/python3.8/site-packages/trimesh/base.py", line 2643, in show
    return scene.show(**kwargs)
  File "/home/kappa95/Documenti/RobotAssisted-AdditiveManufacturing/venv/lib/python3.8/site-packages/trimesh/scene/scene.py", line 1092, in show
    return SceneViewer(self, **kwargs)
  File "/home/kappa95/Documenti/RobotAssisted-AdditiveManufacturing/venv/lib/python3.8/site-packages/trimesh/viewer/windowed.py", line 109, in __init__
    self.reset_view()
  File "/home/kappa95/Documenti/RobotAssisted-AdditiveManufacturing/venv/lib/python3.8/site-packages/trimesh/viewer/windowed.py", line 327, in reset_view
    self.view = {
  File "/home/kappa95/Documenti/RobotAssisted-AdditiveManufacturing/venv/lib/python3.8/site-packages/pyglet/window/__init__.py", line 1008, in view
    with self.ubo as window_block:
AttributeError: 'SceneViewer' object has no attribute 'ubo'
```

I had installed the package with: `python -m pip install trimesh[all]`. The pyglet version installed is: 2.0.0.

How Can I solve?

Thank you so much

**Comment by mikedh** [comment]
Thanks for the report! It looks like pyglet just did a major release (2.0) which changed a bunch of stuff, I'll take a look. In the meantime you may want to temporarily downgrade `pip install --upgrade pyglet=1.5.27`

**Comment by kappa95** [comment]
Great! `pip install --upgrade pyglet==1.5.27` solved! Thank you!
