### ISSUE TITLE
Collada DaeUnsupportedError Unknown scene node (Comment) since trimesh 3.17.0

### ISSUE THREAD

**Issue by stephane-caron** [mikedh/trimesh#1772]
Running the following example from [robot_descriptions.py](https://github.com/robot-descriptions/robot_descriptions.py):

```console
$ python examples/load_in_yourdfpy.py valkyrie
[...]
Traceback (most recent call last):
  File "examples/load_in_yourdfpy.py", line 36, in <module>
    robot = load_robot_description(f"{args.name}_description")
  File "/home/frankd/.local/lib/python3.8/site-packages/robot_descriptions/loaders/yourdfpy.py", line 47, in load_robot_description
    return yourdfpy.URDF.load(module.URDF_PATH)
  File "/home/frankd/.local/lib/python3.8/site-packages/yourdfpy/urdf.py", line 989, in load
    return URDF(robot=URDF._parse_robot(xml_element=xml_root), **kwargs)
  File "/home/frankd/.local/lib/python3.8/site-packages/yourdfpy/urdf.py", line 641, in __init__
    self._scene = self._create_scene(
  File "/home/frankd/.local/lib/python3.8/site-packages/yourdfpy/urdf.py", line 1333, in _create_scene
    self._add_geometries_to_scene(
  File "/home/frankd/.local/lib/python3.8/site-packages/yourdfpy/urdf.py", line 1273, in _add_geometries_to_scene
    new_s = self._geometry2trimeshscene(
  File "/home/frankd/.local/lib/python3.8/site-packages/yourdfpy/urdf.py", line 1221, in _geometry2trimeshscene
    new_s = trimesh.load(
  File "/home/frankd/.local/lib/python3.8/site-packages/trimesh/exchange/load.py", line 129, in load
    loaded = load_mesh(file_obj,
  File "/home/frankd/.local/lib/python3.8/site-packages/trimesh/exchange/load.py", line 212, in load_mesh
    results = loader(file_obj,
  File "/home/frankd/.local/lib/python3.8/site-packages/trimesh/exchange/dae.py", line 50, in load_collada
    c = collada.Collada(
  File "/home/frankd/.local/lib/python3.8/site-packages/collada/__init__.py", line 244, in __init__
    self._loadScenes()
  File "/home/frankd/.local/lib/python3.8/site-packages/collada/__init__.py", line 472, in _loadScenes
    self.handleError(ex)
  File "/home/frankd/.local/lib/python3.8/site-packages/collada/__init__.py", line 470, in _loadScenes
    S = scene.Scene.load(self, scenenode)
  File "/home/frankd/.local/lib/python3.8/site-packages/collada/scene.py", line 916, in load
    collada.handleError(ex)
  File "/home/frankd/.local/lib/python3.8/site-packages/collada/scene.py", line 912, in load
    N = loadNode(collada, nodenode, localscope)
  File "/home/frankd/.local/lib/python3.8/site-packages/collada/scene.py", line 840, in loadNode
    if node.tag == collada.tag('node'): return Node.load(collada, node, localscope)
  File "/home/frankd/.local/lib/python3.8/site-packages/collada/scene.py", line 420, in load
    collada.handleError(ex)
  File "/home/frankd/.local/lib/python3.8/site-packages/collada/scene.py", line 414, in load
    n = loadNode(collada, subnode, localscope)
  File "/home/frankd/.local/lib/python3.8/site-packages/collada/scene.py", line 840, in loadNode
    if node.tag == collada.tag('node'): return Node.load(collada, node, localscope)
  File "/home/frankd/.local/lib/python3.8/site-packages/collada/scene.py", line 420, in load
    collada.handleError(ex)
  File "/home/frankd/.local/lib/python3.8/site-packages/collada/scene.py", line 414, in load
    n = loadNode(collada, subnode, localscope)
  File "/home/frankd/.local/lib/python3.8/site-packages/collada/scene.py", line 840, in loadNode
    if node.tag == collada.tag('node'): return Node.load(collada, node, localscope)
  File "/home/frankd/.local/lib/python3.8/site-packages/collada/scene.py", line 420, in load
    collada.handleError(ex)
  File "/home/frankd/.local/lib/python3.8/site-packages/collada/scene.py", line 414, in load
    n = loadNode(collada, subnode, localscope)
  File "/home/frankd/.local/lib/python3.8/site-packages/collada/scene.py", line 855, in loadNode
    else: raise DaeUnsupportedError('Unknown scene node %s' % str(node.tag))
collada.common.DaeUnsupportedError: DaeUnsupportedError: Unknown scene node <cyfunction Comment at 0x7fde805592b0>
```

This error does not happen with trimesh 3.16.0:

```console
$ pip install trimesh==3.16.0
$ python examples/load_in_yourdfpy.py valkyrie
Robot successfully loaded as <yourdfpy.urdf.URDF object at 0x7f8327a29a30>
```

The offending Collada file is this one: [head_camera.dae](https://gitlab.com/nasa-jsc-robotics/val_description/-/blob/master/model/meshes/multisense/head_camera.dae).

**Comment by mikedh** [comment]
Ah looks like I missed one in https://github.com/mikedh/trimesh/pull/1762/files#diff-0215444d79d1273e6bbd9ffae4e9941e9f7112afc2dcf02063641787a99d5e93

When https://github.com/pycollada/pycollada/pull/133 is released we should only need to list the parent class (`DaeError`) rather than listing them all individually. Should be fixed by #1774
