### ISSUE TITLE
ValueError: ('%s exporter not available!', 'dae')

### ISSUE THREAD

**Issue by swiss-knight** [mikedh/trimesh#1779]
Hello,

I'm trying to get my hands on Trimesh which sounds really great but I am facing an error when trying to export a simple mesh to a collada file on Ubuntu. Here the trace:

```python
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
Type "copyright", "credits" or "license" for more information.

import trimesh

print(trimesh.__version__) # '3.13.5'

final_mesh.export(filepath,'dae')
Traceback (most recent call last):

  File "/tmp/ipykernel_1094839/783368150.py", line 1, in <cell line: 1>
    final_mesh.export(filepath,'dae')

  File "/usr/local/lib/python3.10/dist-packages/trimesh/base.py", line 2742, in export
    return export_mesh(mesh=self,

  File "/usr/local/lib/python3.10/dist-packages/trimesh/exchange/export.py", line 68, in export_mesh
    raise ValueError('%s exporter not available!', file_type)

ValueError: ('%s exporter not available!', 'dae')

```
I don't really understand because the collada file format (`.dae`) seems to be in the code: [export.py#L17](https://github.com/mikedh/trimesh/blob/75ced54d82835150cbd212a56834e7d692a1494e/trimesh/exchange/export.py#L17) & [dae.py](https://github.com/mikedh/trimesh/blob/main/trimesh/exchange/dae.py)
But it is actually not in the [`_mesh_exporters` (export.py#L308-317)](https://github.com/mikedh/trimesh/blob/75ced54d82835150cbd212a56834e7d692a1494e/trimesh/exchange/export.py#L308-L317)

Is there any reason for that? Because the dae exporter is still referenced in the [documentation](https://trimsh.org/trimesh.exchange.dae.html).

Thanks a lot!
Warm Regards.

**Comment by mikedh** [comment]
Hey, yeah `dae` in trimesh is just a thin wrapper around `pycollada`, which you can install with `pip install trimesh[easy]` or `pip install pycollada`
