### ISSUE TITLE
Scene show() crashing

### ISSUE THREAD

**Issue by Eric-Vin** [mikedh/trimesh#1888]
Sometimes when showing a scene in Trimesh, I get a crash with the following error/stacktrace:

```
Traceback (most recent call last):
  File "/home/evin/Projects/Scenic-devel/examples/3d/test.py", line 7, in <module>
    mesh_1.show()
  File "/home/evin/Projects/Scenic-devel/scenic.venv/lib/python3.9/site-packages/trimesh/base.py", line 2726, in show
    return scene.show(**kwargs)
  File "/home/evin/Projects/Scenic-devel/scenic.venv/lib/python3.9/site-packages/trimesh/scene/scene.py", line 1246, in show
    return SceneViewer(self, **kwargs)
  File "/home/evin/Projects/Scenic-devel/scenic.venv/lib/python3.9/site-packages/trimesh/viewer/windowed.py", line 220, in __init__
    pyglet.app.run()
  File "/home/evin/Projects/Scenic-devel/scenic.venv/lib/python3.9/site-packages/pyglet/app/__init__.py", line 107, in run
    event_loop.run()
  File "/home/evin/Projects/Scenic-devel/scenic.venv/lib/python3.9/site-packages/pyglet/app/base.py", line 170, in run
    platform_event_loop.step(timeout)
  File "/home/evin/Projects/Scenic-devel/scenic.venv/lib/python3.9/site-packages/pyglet/app/xlib.py", line 121, in step
    device.select()
  File "/home/evin/Projects/Scenic-devel/scenic.venv/lib/python3.9/site-packages/pyglet/canvas/xlib.py", line 205, in select
    dispatch(e)
  File "/home/evin/Projects/Scenic-devel/scenic.venv/lib/python3.9/site-packages/pyglet/window/xlib/__init__.py", line 984, in dispatch_platform_event_view
    event_handler(e)
  File "/home/evin/Projects/Scenic-devel/scenic.venv/lib/python3.9/site-packages/pyglet/window/xlib/__init__.py", line 1211, in _event_motionnotify_view
    self.dispatch_event('on_mouse_drag', x, y, dx, dy, buttons, modifiers)
  File "/home/evin/Projects/Scenic-devel/scenic.venv/lib/python3.9/site-packages/pyglet/window/__init__.py", line 1353, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "/home/evin/Projects/Scenic-devel/scenic.venv/lib/python3.9/site-packages/pyglet/event.py", line 420, in dispatch_event
    raise e
  File "/home/evin/Projects/Scenic-devel/scenic.venv/lib/python3.9/site-packages/pyglet/event.py", line 415, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/home/evin/Projects/Scenic-devel/scenic.venv/lib/python3.9/site-packages/trimesh/viewer/windowed.py", line 648, in on_mouse_drag
    self.view['ball'].drag(np.array([x, y]))
  File "/home/evin/Projects/Scenic-devel/scenic.venv/lib/python3.9/site-packages/trimesh/viewer/trackball.py", line 128, in drag
    dx, dy = point - self._pdown
AttributeError: 'Trackball' object has no attribute '_pdown'
```

This is the program that triggered the crash:
```
import trimesh
from trimesh.transformations import translation_matrix

mesh_1 = trimesh.creation.box((1,1,1))
mesh_1.apply_transform(translation_matrix((1000,1000,1000)))

render_scene = trimesh.scene.Scene()
render_scene.add_geometry(mesh_1)
render_scene.show(flags={'axis': True})
```

Any idea how to fix this crash?

**Comment by mikedh** [comment]
Hey, that example doesn't crash for me, although it looks like it does depend on pyglet always triggering `down` before `drag` which maybe the event loop does something out of order on different operating systems. I just added a simple check which makes `drag` a no-op if `_pdown` doesn't exist yet. 

Also, if you're setting the axis state you probably want it to be `'world'` instead of `True` as it's a set of 4 values: `states = [False, 'world', 'all', 'without_world']`

```
import numpy as np
import trimesh

if __name__ == '__main__':

    from trimesh.transformations import translation_matrix

    mesh_1 = trimesh.creation.box((1,1,1))
    mesh_1.apply_transform(translation_matrix((1000,1000,1000)))

    render_scene = trimesh.scene.Scene()
    render_scene.add_geometry(mesh_1)
    render_scene.show(flags={'axis': 'world'})


```

**Comment by Eric-Vin** [comment]
Great, thanks so much for the help and I'll make the axis change!
