### ISSUE TITLE
trimesh cannot load some ply files

### ISSUE THREAD

**Issue by Guptajakala** [mikedh/trimesh#1911]
When loading this [ply file](https://drive.google.com/file/d/1XuCqXU7Hlw-2bNJNuwFn7PHlYJ1MRAvl/view?usp=sharing), trimesh gives below error. However, meshlab and blender both can read the file fine. Would it be possible to change that value error to warning instead?
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/py/.conda/envs/py/lib/python3.8/site-packages/trimesh/exchange/load.py", line 127, in load
    loaded = load_mesh(file_obj,
  File "/home/py/.conda/envs/py/lib/python3.8/site-packages/trimesh/constants.py", line 153, in timed
    result = method(*args, **kwargs)
  File "/home/py/.conda/envs/py/lib/python3.8/site-packages/trimesh/exchange/load.py", line 209, in load_mesh
    results = mesh_loaders[file_type](file_obj,
  File "/home/py/.conda/envs/py/lib/python3.8/site-packages/trimesh/exchange/ply.py", line 105, in load_ply
    ply_binary(elements, file_obj)
  File "/home/py/.conda/envs/py/lib/python3.8/site-packages/trimesh/exchange/ply.py", line 881, in ply_binary
    raise ValueError('File is unexpected length!')
ValueError: File is unexpected length!
```

trimesh version: 3.14.1

**Comment by ElHouas** [comment]
I am facing the same issue with a ply mesh obtained from blender. How did you solve the problem?

**Comment by mikedh** [comment]
Hey, if you comment out that `ValueError` does your file load correctly? Can you share a small example file that demonstrates this for tests? Thanks for the report!

**Comment by Guptajakala** [comment]
Hi, here is the sample file for reproducing
https://drive.google.com/file/d/1XuCqXU7Hlw-2bNJNuwFn7PHlYJ1MRAvl/view?usp=sharing

**Comment by geyang** [comment]
Same issue here. Commenting out does not help.

**Comment by ElHouas** [comment]
In my case, I found that the mesh contained some quad faces and trimesh could not load it if the file was saved as binary. Then, as a solution, I've found that exporting the blend file as ply in ASCII format solves this problem.

I hope is helpful for others :)
