### ISSUE TITLE
Render a colored Sphere in Scene, Sphere constructor crashes: 'Sphere' object has no attribute 'primitive'

### ISSUE THREAD

**Issue by manuel-koch** [mikedh/trimesh#1924]
I want to use the Sphere primitive and render it in scene with selected color.
This seem to work when using an intermediate trimesh object but crashes for a Scene primitive.
Is this (intermediate) way the right way to add a colored sphere to a scene ?

It seems to work using an intermediate trimesh geometry
```python
from trimesh import Scene, Trimesh
from trimesh.primitives import Sphere

sphere = Sphere()
sphere_tm = Trimesh(vertices=sphere.vertices, faces=sphere.faces, face_colors=(255,130,130))
sphere.apply_translation([3,0,0])
scene = Scene()
scene.add_geometry(sphere)
scene.add_geometry(sphere_tm)
scene.show(smooth=False)
```

but a shortcut to use a sphere primitive directly doesn't work
```python
>>> sphere = Sphere(face_colors=(0,0,0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/python_env/lib/python3.10/site-packages/trimesh/primitives.py", line 468, in __init__
    super(Sphere, self).__init__(*args, **kwargs)
  File "/python_env/lib/python3.10/site-packages/trimesh/primitives.py", line 37, in __init__
    super(_Primitive, self).__init__(*args, **kwargs)
  File "/python_env/lib/python3.10/site-packages/trimesh/base.py", line 129, in __init__
    self.visual = create_visual(
  File "/python_env/lib/python3.10/site-packages/trimesh/visual/objects.py", line 33, in create_visual
    return ColorVisuals(**kwargs)
  File "/python_env/lib/python3.10/site-packages/trimesh/visual/color.py", line 74, in __init__
    self.face_colors = face_colors
  File "/python_env/lib/python3.10/site-packages/trimesh/visual/color.py", line 210, in face_colors
    count = len(self.mesh.faces)
  File "/python_env/lib/python3.10/site-packages/trimesh/primitives.py", line 49, in faces
    self._create_mesh()
  File "/python_env/lib/python3.10/site-packages/trimesh/primitives.py", line 558, in _create_mesh
    unit = creation.icosphere(subdivisions=self.primitive.subdivisions)
AttributeError: 'Sphere' object has no attribute 'primitive'
```

Using MacOS Ventura 13.3.1 (22E261) on arm64
```
$ python3 --version
Python 3.10.6

$ pip3 list
Package            Version
------------------ --------
aiohttp            3.8.4
aiosignal          1.3.1
async-timeout      4.0.2
attrs              23.1.0
black              22.6.0
build              0.10.0
certifi            2023.5.7
chardet            5.1.0
charset-normalizer 3.1.0
click              8.1.3
colorlog           6.7.0
frozenlist         1.3.3
idna               3.4
iniconfig          2.0.0
isort              5.10.1
jsonschema         4.17.3
lxml               4.9.2
mpmath             1.3.0
msgpack            1.0.5
multidict          6.0.4
multipledispatch   0.6.0
mypy-extensions    1.0.0
networkx           3.1
numpy              1.24.3
packaging          23.1
parameterized      0.8.1
pathspec           0.11.1
Pillow             9.5.0
pip                23.1.2
pip-tools          6.13.0
platformdirs       3.5.0
pluggy             1.0.0
py                 1.11.0
pycollada          0.7.2
pydantic           1.9.2
pyglet             1.5.27
pyproject_hooks    1.0.0
pyrr               0.10.3
pyrsistent         0.19.3
pytest             7.1.3
pytest-env         0.6.2
python-dateutil    2.8.2
requests           2.30.0
Rtree              1.0.1
scipy              1.10.1
setuptools         63.2.0
shapely            2.0.1
six                1.16.0
svg.path           6.3
sympy              1.12
tomli              2.0.1
trimesh            3.12.9
typing_extensions  4.5.0
urllib3            2.0.2
wheel              0.40.0
xxhash             3.2.0
yarl               1.9.2
```

**Comment by manuel-koch** [comment]
I retried it with latest trimesh version 3.21.6 too with same crash.
