### ISSUE TITLE
How can I get "mesh.visual.face_colors" from mesh using uv texture map??

### ISSUE THREAD

**Issue by SangHunHan92** [mikedh/trimesh#2013]
Hi. I am rendering textured mesh using trimesh.
How can I render color from uv texture map?

Following is example of my rendering code:
```
im = Image.open(texture_file)
material = trimesh.visual.texture.SimpleMaterial(image=im)
color_visuals = trimesh.visual.TextureVisuals(uv=uv, image=im, material=material)
mesh = trimesh.Trimesh(vertices=vertices, faces=faces, visual=color_visuals, use_embree=True)

scene = mesh.scene()
mesh.scene = scene
pers_origins, pers_vectors, pers_pixels = mesh.scene.camera_rays()
pers_points, pers_index_ray, pers_index_tri = mesh.ray.intersects_location(pers_origins,
                                                                               pers_vectors,
                                                                               multiple_hits=True)

pers_colors = mesh.visual.face_colors[pers_index_tri] / 255.0
```

But, it cause error "AttributeError: 'TextureVisuals' object has no attribute 'face_colors'"

Also, I tried to get color from to_color(), but...
```
a = mesh.visual.to_color()
a.vertex_colors
TrackedArray([[ 35,  33,  36, 255],
              [ 34,  32,  35, 255],
              [ 38,  36,  39, 255],
              ...,
              [ 35,  33,  36, 255],
              [ 38,  36,  41, 255],
              [ 44,  43,  48, 255]], dtype=uint8)
a.face_colors
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/trimesh/visual/color.py", line 172, in face_colors
    return self._get_colors(name='face')
  File "/usr/local/lib/python3.8/dist-packages/trimesh/visual/color.py", line 331, in _get_colors
    faces=self.mesh.faces)
AttributeError: 'NoneType' object has no attribute 'faces'
```

I can only get vertex color of mesh.

How can I get "face color" or "color of the intersection of mesh and ray" ??

or can I get color from following code??
```
mesh.scene.camera_rays()
mesh.ray.intersects_location()
```

Thank you very much for your help.

**Comment by mikedh** [comment]
Hey, if you assign the visual to the mesh it adds the reference to look at the faces:

```
In [3]: m = trimesh.load('models/fuze.obj')

In [4]: m.visual
Out[4]: <trimesh.visual.texture.TextureVisuals at 0x7f9296f510d0>

In [5]: m.visual = m.visual.to_color()

In [6]: m.visual.kind
Out[6]: 'vertex'

In [7]: m.visual.face_colors
Out[7]: 
TrackedArray([[127, 127, 127, 255],
              [127, 127, 127, 255],
              [127, 127, 127, 255],
              ...,
              [127,  66,  73, 255],
              [143,   0,  44, 255],
              [109,  59,  70, 255]], dtype=uint8)
```
