### ISSUE TITLE
pip install missing some dependencies

### ISSUE THREAD

**Issue by jgostick** [mikedh/trimesh#21]
The ```pip install trimesh``` worked fine, but when I attempted to import the module (```import trimesh```) it failed since shapely was not found.  

Info: windows 10, WinPython 3.5.1.2, Python 3.5, 64bit

**Comment by mikedh** [comment]
Hmm, the shapely imports should all be wrapped in try-except blocks, maybe one slipped in. I'll take a look tonight, in the meantime would you mind posting a traceback? Thanks!

**Comment by jgostick** [comment]
2016-07-06 10:55:44,652 | WARNING  | trimesh.<module> | graph-tool unavailable, some operations will be much slower
2016-07-06 10:55:44,852 | WARNING  | trimesh.<module> | trimesh.path unavailable, try pip install shapely!
Traceback (most recent call last):
  File "C:\WinPy3512\python-3.5.1.amd64\lib\site-packages\trimesh\base.py", line 35, in <module>
    from .path.io.misc import faces_to_path
  File "C:\WinPy3512\python-3.5.1.amd64\lib\site-packages\trimesh\path\__init__.py", line 1, in <module>
    from .path import Path2D, Path3D
  File "C:\WinPy3512\python-3.5.1.amd64\lib\site-packages\trimesh\path\path.py", line 10, in <module>
    from shapely.geometry import Polygon
ImportError: No module named 'shapely'
2016-07-06 10:55:44,890 | WARNING  | trimesh.<module> | pyassimp unavailable, using only native loaders
2016-07-06 10:55:44,906 | WARNING  | trimesh.<module> | No path functionality available!
Traceback (most recent call last):
  File "C:\WinPy3512\python-3.5.1.amd64\lib\site-packages\trimesh\io\load.py", line 17, in <module>
    from ..path.io.load import load_path, path_formats
  File "C:\WinPy3512\python-3.5.1.amd64\lib\site-packages\trimesh\path\__init__.py", line 1, in <module>
    from .path import Path2D, Path3D
  File "C:\WinPy3512\python-3.5.1.amd64\lib\site-packages\trimesh\path\path.py", line 10, in <module>
    from shapely.geometry import Polygon
ImportError: No module named 'shapely'
2016-07-06 10:55:44,921 | WARNING  | trimesh.<module> | shapely unavilable
Traceback (most recent call last):
  File "C:\WinPy3512\python-3.5.1.amd64\lib\site-packages\trimesh\creation.py", line 18, in <module>
    from shapely.geometry import Polygon
ImportError: No module named 'shapely'

**Comment by mikedh** [comment]
I see, was this on import or was this on trying to use path functionality, which does require shapely. Did you run the 'optional dependencies' bit in the readme? Or as extras:

pip install trimesh[all]

**Comment by jgostick** [comment]
this was on ```import trimesh```

**Comment by mikedh** [comment]
So this worked for me in an isolated virtualenv. I think trimesh imported successfully, I just had the traceback left in the log message. That traceback is sent to the logger through an log.warning('blah blah', exc_info=True).  All of the places its complaining about the ImportError are inside a try/except block. If you run:
```
In [1]: import trimesh

In [2]: dir(trimesh)
```

It should print available methods.

**Comment by jgostick** [comment]
Ah, I see.  trimesh did actually import, but the try/except blocks aren't muting the tracebacks.  Thanks!
