### ISSUE TITLE
Unable to plot 3d points using trimesh 2.35.6-py_0 conda forge version

### ISSUE THREAD

**Issue by Adamwgoh** [mikedh/trimesh#234]
I am not entirely sure this is an error, but when I installed trimesh using `conda install -c conda-forge trimesh` to obtain trimesh 2.35.6-py_0. My objective was to be able to plot a numpy array (m,3) directly.

Reproduce code:
```
v = np.random.random( (100,3))
p = trimesh.points.PointCloud(v)
p.show()
```

Error: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adamg/anaconda2/envs/venvpy3/lib/python3.6/site-packages/trimesh/points.py", line 523, in show
    self.scene().show()
  File "/home/adamg/anaconda2/envs/venvpy3/lib/python3.6/site-packages/trimesh/scene/scene.py", line 737, in show
    return SceneViewer(self, **kwargs)
  File "/home/adamg/anaconda2/envs/venvpy3/lib/python3.6/site-packages/trimesh/scene/viewer.py", line 84, in __init__
    pyglet.app.run()
  File "/home/adamg/anaconda2/envs/venvpy3/lib/python3.6/site-packages/pyglet/app/__init__.py", line 138, in run
    event_loop.run()
  File "/home/adamg/anaconda2/envs/venvpy3/lib/python3.6/site-packages/pyglet/app/base.py", line 142, in run
    self._run()
  File "/home/adamg/anaconda2/envs/venvpy3/lib/python3.6/site-packages/pyglet/app/base.py", line 154, in _run
    timeout = self.idle()
  File "/home/adamg/anaconda2/envs/venvpy3/lib/python3.6/site-packages/pyglet/app/base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "/home/adamg/anaconda2/envs/venvpy3/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "/home/adamg/anaconda2/envs/venvpy3/lib/python3.6/site-packages/pyglet/event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/home/adamg/anaconda2/envs/venvpy3/lib/python3.6/site-packages/trimesh/scene/viewer.py", line 263, in on_draw
    self._update_meshes()
  File "/home/adamg/anaconda2/envs/venvpy3/lib/python3.6/site-packages/trimesh/scene/viewer.py", line 94, in _update_meshes
    if self.vertex_list_hash[name] != geometry_hash(mesh):
KeyError: 'geometry_0'
```

However, downgrading it to 2.34.2-py_0 using conda forge seems to solve the issue. Apologies in advance if I have missed out something, or this is a build dependent issue.

**Comment by mikedh** [comment]
No worries- that code sample should totally work. I'll try it on a couple different platforms and see if I can reproduce. Thanks for the report!

**Comment by PHPirates** [comment]
This seems to happen if you previously messed up another mesh, so it's a bit confusing error.
Example to reproduce:
```python
import trimesh
trimesh.Trimesh(vertices=[[0, 0], [0, 0], [0, 1]], faces=[[0, 1, 2]]).show()  # Mistake
trimesh.Trimesh(vertices=[[0, 0, 0], [0, 0, 0], [0, 1, 0]], faces=[[0, 1, 2]]).show()  # Correct, but raising this error: KeyError: 'geometry_0'
```

Python 3.9.0
trimesh 3.8.18
pyglet 1.5.11
