### ISSUE TITLE
The open file is not closed if the UnicodeDecodeError exception is triggered

### ISSUE THREAD

**Issue by bolofili** [mikedh/trimesh#285]
I want to report the followin issue.

`import trimesh`
`mesh = trimesh.load('model.3ds')`

Running the code above the loaded model remains open and then I can't delete it from my FileSystem.

**Comment by mikedh** [comment]
Thanks for the report! I added some clean- up logic in that case in https://github.com/mikedh/trimesh/commit/07caf30a4d83d8365c8bfdb18aaed14b6d3abedd, let me know if that fixes it for you.

Also, were you trying to load 3DS with `pyassimp` via trimesh?

**Comment by bolofili** [comment]
Thanks for your answare! Unfortunately your commit doesn't fixed the problem. I think you should call the close() when the load() method has loaded the file. I don't know how do you have done the library but I was wondering if you implement this:

`with open(model_path) as model:`

**Comment by mikedh** [comment]
Generally the function does that, in this case it is probably crashing somewhere before `load` gets to its cleanup logic. It is probably inside `parse_file_args`. Could you post a full traceback?

**Comment by bolofili** [comment]
Sorry, I badly explained myself. The file remains open because during the `load()` an exception is triggered.
Here the traceback with `KeyError`

```
Traceback (most recent call last):
  File "D:\Download\desamanerax\desawide\media\desawide\geometries\mesh.py", line 3, in <module>
    mesh = trimesh.load_mesh('model.3ds')
  File "C:\Users\Filippo\AppData\Local\Programs\Python\Python37\lib\site-packages\trimesh\constants.py", line 128, in timed
    result = method(*args, **kwargs)
  File "C:\Users\Filippo\AppData\Local\Programs\Python\Python37\lib\site-packages\trimesh\exchange\load.py", line 201, in load_mesh
    results = mesh_loaders[file_type](file_obj,
KeyError: '3ds'
```
The same result if I change the extension of the file to `.stl` getting `HeaderError` and `UnicodeDecodeError`

Traceback (most recent call last):
  File "C:\Users\Filippo\AppData\Local\Programs\Python\Python37\lib\site-packages\trimesh\exchange\stl.py", line 44, in load_stl
    return load_stl_binary(file_obj)
  File "C:\Users\Filippo\AppData\Local\Programs\Python\Python37\lib\site-packages\trimesh\exchange\stl.py", line 112, in load_stl_binary
    raise HeaderError('Binary STL has incorrect length in header!')
trimesh.exchange.stl.HeaderError: Binary STL has incorrect length in header!

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "D:\Download\desamanerax\desawide\media\desawide\geometries\mesh.py", line 3, in <module>
    mesh = trimesh.load_mesh('model.3ds.stl')
  File "C:\Users\Filippo\AppData\Local\Programs\Python\Python37\lib\site-packages\trimesh\constants.py", line 128, in timed
    result = method(*args, **kwargs)
  File "C:\Users\Filippo\AppData\Local\Programs\Python\Python37\lib\site-packages\trimesh\exchange\load.py", line 204, in load_mesh
    **kwargs)
  File "C:\Users\Filippo\AppData\Local\Programs\Python\Python37\lib\site-packages\trimesh\exchange\stl.py", line 51, in load_stl
    return load_stl_ascii(file_obj)
  File "C:\Users\Filippo\AppData\Local\Programs\Python\Python37\lib\site-packages\trimesh\exchange\stl.py", line 157, in load_stl_ascii
    text = text.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 9: invalid start byte
```

The exceptions work very well but the file remains open after those.

**Comment by mikedh** [comment]
Ah, I was able to reproduce thanks! I see you're calling `trimesh.load_mesh` rather than `trimesh.load` which had the previous fix. Hopefully fixed in: https://github.com/mikedh/trimesh/commit/5af860639d4f1700f27eaebe81b4f7901334dbf2

**Comment by bolofili** [comment]
Thanks, it works!!

If you want I can close the issue.

**Comment by mikedh** [comment]
Glad it worked!
