### ISSUE TITLE
 MTL file

### ISSUE THREAD

**Issue by gperonato** [mikedh/trimesh#332]
Hi, it is not very clear to me how to import a MTL file associated to an OBJ file using a resolver. It would be nice if you can add some sample code lines. Everything else is very intuitive and works smoothly. Thanks a lot for your work!

**Comment by mikedh** [comment]
Hey, try running `trimesh.util.attach_to_log()` before loading- I suspect it might be not finding the MTL for some reason. If you're using `trimesh.load`, you shouldn't need to create a resolver manually, although here's the manual process:
```
In [1]: import trimesh

In [2]: trimesh.util.attach_to_log()

# will create correct resolver and load MTL
In [3]: m = trimesh.load('models/fuze.obj')
DEBUG              load.py:211   loaded mesh using load_wavefront
DEBUG           caching.py:104   is_empty was not in cache, executed in 0.000011
DEBUG         constants.py:131   load_mesh executed in 0.0258 seconds.

# manually create a resolver
In [4]: file_name = 'models/fuze.obj'

In [5]: resolver = trimesh.visual.resolvers.FilePathResolver(file_name)

In [6]: with open(file_name, 'r') as f:
   ...:     kwargs = trimesh.exchange.wavefront.load_wavefront(f, resolver=resolver)
   ...:     

In [7]: kwargs
Out[7]: 
[{'faces': array([[  0,   5,   1],
         [  0,   6,   5],
         [  2,   0,   3],
         ...,
         [186, 532, 216],
         [397, 244, 260],
         [116, 658, 605]]),
  'metadata': {},
  'vertex_normals': array([[ 0.     ,  0.     , -6.28318],
         [ 0.     ,  0.     , -6.28318],
         [ 0.00004,  0.     , -6.28318],
         ...,
         [ 0.31089, -3.89323,  3.00075],
         [ 0.31089, -3.89323,  3.00075],
         [-4.26178, -4.38659,  1.17074]]),
  'vertices': array([[ 0.00205, -0.00287,  0.00403],
         [ 0.00205,  0.00655,  0.00403],
         [ 0.01382, -0.00758,  0.00403],
         ...,
         [ 0.00211, -0.0155 ,  0.21693],
         [ 0.00211, -0.0155 ,  0.21693],
         [-0.02359, -0.02443,  0.11301]]),
  'visual': <trimesh.visual.texture.TextureVisuals at 0x7fb0e51bb550>}]

```

**Comment by gperonato** [comment]
Hi Mike, thanks for the prompt reply. I think there is indeed a problem loading the MTL file. Here's the log:
```
[2019-03-01 17:46:19] ERROR   (wavefront.py:178) failed to load texture: material_0
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\trimesh\exchange\wavefront.py", line 169, in append_mesh
    file_data = resolver.get(file_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\trimesh\visual\resolvers.py", line 67, in get
    with open(os.path.join(self.parent, name), 'rb') as f:
  File "C:\ProgramData\Anaconda3\lib\ntpath.py", line 115, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\ProgramData\Anaconda3\lib\genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
[2019-03-01 17:46:19] DEBUG   (load.py:211) loaded mesh using load_wavefront
[2019-03-01 17:46:19] DEBUG   (caching.py:104) is_empty was not in cache, executed in 0.000000
[2019-03-01 17:46:19] DEBUG   (constants.py:131) load_mesh executed in 0.0127 seconds.
```

**Comment by mikedh** [comment]
It looks like you called `trimesh.load` on a file object, so you would have to manually pass a resolver as the file object has no idea of where other files are relative to it.  If you load based on a file name it will create a `FilePathResolver` for you, which just searches the source directory for the requested file. For other types of sources (ZIP archives, file paths, web resources) the resolver abstracts how you get stuff into a single `resolver.get(asset_name)` call. Here's an example of how it's handled for web assets:

https://github.com/mikedh/trimesh/blob/6a9889466b8baa478179681acb79c44524b2abe1/trimesh/exchange/load.py#L331-L361

**Comment by gperonato** [comment]
Hi Mike,

I am sorry, I realized that the texture image was missing, now the material importer does work with the sample model fuze.obj without passing the resolver.
However, I am not able to import the material file from another model I have. There is no texture here, only colors, and the normals are not defined in the OBJ file. The mesh is correctly imported, but the colors in m.visual.face_colors are the default ones... 

_test.obj_
```
mtllib 3d.mtl
v 646050.541 6640277.831 12.04
v 646054.459 6640273.257 12.04
v 646057.997 6640276.291 12.04
v 646054.078 6640280.864 12.04
v 646050.541 6640277.831 6.70
v 646054.459 6640273.257 6.70
v 646054.078 6640280.864 6.70
v 646057.997 6640276.291 6.70
o 6b417a95-02ec-4bb2-bd15-2791f5748769
usemtl Roof
f 1 2 3
f 1 3 4
usemtl Wall
f 5 6 1
f 1 6 2
f 7 5 4
f 4 5 1
f 8 7 3
f 3 7 4
f 6 8 2
f 2 8 3
usemtl Floor
f 5 8 6
f 5 7 8
```
3d.mtl
```
newmtl Roof
Ka 0.8700 0.2600 0.2800
Kd 0.8700 0.2600 0.2800
Ks 0.8700 0.2600 0.2800
illum 2
Ns 60.0000

newmtl Wall
Ka 0.8500 0.8500 0.8500
Kd 0.8500 0.8500 0.8500
Ks 0.8500 0.8500 0.8500
illum 2
Ns 60.0000

newmtl Floor
Ka 0.4500 0.4500 0.4500
Kd 0.4500 0.4500 0.4500
Ks 0.4500 0.4500 0.4500
illum 2
Ns 60.0000
```

**Comment by mikedh** [comment]
Hey, as with #350, that's currently not supported. I'm in the middle of an OBJ re-write, and have added this to the scope.

**Comment by gperonato** [comment]
Thanks for the follow up! I am looking forward to this.

**Comment by mikedh** [comment]
Combining into #391. Thanks for the report!
