### ISSUE TITLE
No backends available for convex decomposition

### ISSUE THREAD

**Issue by frk1993** [mikedh/trimesh#404]
Hi,
I get following ValueError: No backends available for convex decomposition

How I can solve this problem ?

Best Regards

**Comment by mikedh** [comment]
Hey, convex decompositions use [VHACD](https://github.com/kmammou/v-hacd). You can compile it and copy the binary into your `PATH`, or in Docker we use a bash script to [fetch a static binary](https://github.com/mikedh/trimesh/blob/30a423b884903905aba82408255f02dec0b33175/docker/builds/vhacd.bash) which should work on Linux systems.

**Comment by frk1993** [comment]
Thanks for the answer. I could solve this problem, but now I get following errors. maybe you can help me further.

`Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/trimesh/exchange/urdf.py", line 51, in export_urdf
    convex_pieces = convex_decomposition(mesh, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/trimesh/decomposition.py", line 18, in convex_decomposition
    result = _engines[engine](mesh, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/trimesh/decomposition.py", line 24, in decomposition_automatic
    result = interfaces.vhacd.convex_decomposition(mesh, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/trimesh/interfaces/vhacd.py", line 42, in convex_decomposition
    result = vhacd.run(_vhacd_executable + argstring)
  File "/anaconda3/lib/python3.6/site-packages/trimesh/interfaces/generic.py", line 70, in run
    stderr=subprocess.STDOUT)
  File "/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/testVHACD', '--input', '/var/folders/72/55nkj3991zd1w5m1zngmx2v80000gn/T/tmp3db7dnqw.obj', '--output', '/var/folders/72/55nkj3991zd1w5m1zngmx2v80000gn/T/tmpsaglxt8q.obj', '--log', '/var/folders/72/55nkj3991zd1w5m1zngmx2v80000gn/T/tmp__fw3aue']' died with <Signals.SIGABRT: 6>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_mask_dataset.py", line 279, in generate_segmask_dataset
    env.reset()
  File "/Users/frktna/Desktop/Masterarbeit/SDmaskRCNN/sd-maskrcnn/sd_maskrcnn/envs/bin_heap_env.py", line 165, in reset
    self._reset_state_space()
  File "/Users/frktna/Desktop/Masterarbeit/SDmaskRCNN/sd-maskrcnn/sd_maskrcnn/envs/bin_heap_env.py", line 85, in _reset_state_space
    state = self._state_space.sample()
  File "/Users/frktna/Desktop/Masterarbeit/SDmaskRCNN/sd-maskrcnn/sd_maskrcnn/envs/state_spaces.py", line 427, in sample
    heap_state = self.heap.sample()
  File "/Users/frktna/Desktop/Masterarbeit/SDmaskRCNN/sd-maskrcnn/sd_maskrcnn/envs/state_spaces.py", line 215, in sample
    self._physics_engine.add(workspace_obj, static=True)
  File "/Users/frktna/Desktop/Masterarbeit/SDmaskRCNN/sd-maskrcnn/sd_maskrcnn/envs/physics_engine.py", line 89, in add
    trimesh.exchange.export.export_urdf(geometry, urdf_dir)
  File "/anaconda3/lib/python3.6/site-packages/trimesh/exchange/urdf.py", line 57, in export_urdf
    convex_pieces = [mesh.convex_hull]
  File "/anaconda3/lib/python3.6/site-packages/trimesh/caching.py", line 99, in get_cached
    value = function(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/trimesh/base.py", line 1956, in convex_hull
    hull = convex.convex_hull(self)
  File "/anaconda3/lib/python3.6/site-packages/trimesh/convex.py", line 53, in convex_hull
    qhull_options=qhull_options)
  File "qhull.pyx", line 2359, in scipy.spatial.qhull.ConvexHull.__init__
  File "qhull.pyx", line 354, in scipy.spatial.qhull._Qhull.__init__
scipy.spatial.qhull.QhullError: QH7023 qhull warning: unknown 'Q' qhull option n, rest ignored
QH6022 qhull input error: 2'th dimension's new bounds [-0.5, 0.5] too wide for
existing bounds [ 0,  0]

While executing:  | qhull i QbB Pp Qt QJn
Options selected for Qhull 2015.2.r 2016/01/18:
  run-id 570369392  incidence  QbBound-unit-box 0.5  Pprecision-ignore
  Qtriangulate
`

Thanks a lot.

**Comment by mikedh** [comment]
Superceded by other issue- thanks for the report!
