### ISSUE TITLE
Pyinstaller issues

### ISSUE THREAD

**Issue by deepankarpal1985** [mikedh/trimesh#412]
How to make this work with Pyinstaller

Gives this error
Traceback (most recent call last):
  File "Temp_extractor.py", line 18, in <module>
  File "mesh_voxel.py", line 31, in voxelmesher2
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\dpal\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\trimesh\__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\dpal\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\trimesh\base.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\dpal\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\trimesh\units.py", line 15, in <module>
  File "site-packages\trimesh\resources\__init__.py", line 20, in get_resource
  File "site-packages\pkg_resources\__init__.py", line 1157, in resource_string
  File "site-packages\pkg_resources\__init__.py", line 1401, in get_resource_string
  File "site-packages\pkg_resources\__init__.py", line 1540, in _get
  File "c:\users\dpal\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 475, in get_data
    with open(path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dpal\\Documents\\ansysdev\\Pythonthermalsolver\\dist\\Temp_extractor\\trimesh\\resources\\units_to_inches.json'
[15260] Failed to execute script Temp_extractor

**Comment by mikedh** [comment]
Oh interesting, it looks like `pyinstaller` isn't copying the files specified in the `package_data` field in `setup.py`. 

[This might be related](https://stackoverflow.com/questions/9689816/installing-data-files-into-site-packages-with-setup-py). Maybe try some variant of adding `trimesh/resources` to `MANIFEST.in`?

**Comment by mikedh** [comment]
Added to requested enhancements list, closing for now.

**Comment by mjd3** [comment]
Looks like adding ```include_package_data=True``` to ```setup.py``` could help with this (see [answer here](https://stackoverflow.com/a/1857436))?

**Comment by ericeasthope** [comment]
Have there been developments on this? AFAIK there isn't another clean way to use `trimesh` in production without support for `pyinstaller`. I wouldn't call support for production builds an "enhancement" ...

**Comment by mikedh** [comment]
Hey, most of the live applications using trimesh (including the ones I work on) run as backend services in docker containers. There are pre-built images based on `debian:buster-slim` on docker hub that are rebuilt on every release.

That being said, I would be happy to accept PR's to fix issues with pyinstaller and run it in unit tests.

**Comment by JOUV** [comment]
Hiya, I'm trying to compile a python script with pyinstaller and although I can get test files working, the script that used trimesh ends with this error when I try to run the exe: 

"Traceback (most recent call last):
  File "example.py", line 12, in <module>
ModuleNotFoundError: No module named 'trimesh'
[25704] Failed to execute script example"

Any ideas on how to fix this? Is there a command switch to use with pyinstaller to force the use of trimesh? Currently all I'm using is "pyinstaller --onefile example.py".
