### ISSUE TITLE
Need more than 3 values to unpack

### ISSUE THREAD

**Issue by science-code** [mikedh/trimesh#458]
Problem: Cannot load trimesh inside Python 2.7.12 on Ubuntu 16.04 (although it used to work a couple of months ago).
Please find the log below:

Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import trimesh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mihai/.local/lib/python2.7/site-packages/trimesh/__init__.py", line 27, in <module>
    from .exchange.load import (load,
  File "/home/mihai/.local/lib/python2.7/site-packages/trimesh/exchange/load.py", line 17, in <module>
    from .assimp import _assimp_loaders
  File "/home/mihai/.local/lib/python2.7/site-packages/trimesh/exchange/assimp.py", line 265, in <module>
    import pyassimp
  File "/usr/lib/python2.7/dist-packages/pyassimp/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/lib/python2.7/dist-packages/pyassimp/core.py", line 29, in <module>
    class AssimpLib(object):
  File "/usr/lib/python2.7/dist-packages/pyassimp/core.py", line 33, in AssimpLib
    load, load_mem, release, dll = helper.search_library()
ValueError: need more than 3 values to unpack

**Comment by mikedh** [comment]
Ah, assimp is throwing a `ValueError` rather than an `ImportError`, I more aggressively wrapped the assimp imports in https://github.com/mikedh/trimesh/commit/5aab6ade29013341868828fd6612676595f943ac which should cover this case, and should release to pypi when the build finishes.

Thanks for the report!

**Comment by science-code** [comment]
@mikedh thanks for the reply! Will there be a fix anytime soon?
Kind regards.

**Comment by mikedh** [comment]
Hey, the `trimesh` fix should be up on pypi now, which you can get with `pip install trimesh --upgrade`. I couldn't speak to`pyassimp`, but they are in a tough situation with regards to system level libraries and it seems unlikely to be resolved any time soon.

**Comment by science-code** [comment]
Thanks! It's working now! Issue solved.
