### ISSUE TITLE
Errors loading .ply files

### ISSUE THREAD

**Issue by patrikhuber** [mikedh/trimesh#49]
Hi,

I've not been able to load .ply files with vertex colours, neither ASCII nor binary. These files open fine in Meshlab, Blender and 3D Builder.

Basically what I am trying to do is load and view a mesh with vertex colours. Is that not something that is supported in trimesh or in the viewer? If I load an obj with vertex colours, it just displays the shape, no colours. Converting to .ply files is even less successful:

I'm getting various errors, depending on whether I use binary or ASCII ply files:

```
mesh = trimesh.load_mesh(r"mesh_ascii.ply")
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2017.1\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\Users\Patrik\Envs\eos-py\lib\site-packages\trimesh\constants.py", line 125, in timed
    result = method(*args, **kwargs)
  File "C:\Users\Patrik\Envs\eos-py\lib\site-packages\trimesh\io\load.py", line 111, in load_mesh
    file_type)
  File "C:\Users\Patrik\Envs\eos-py\lib\site-packages\trimesh\io\ply.py", line 35, in load_ply
    ply_ascii(elements, file_obj)
  File "C:\Users\Patrik\Envs\eos-py\lib\site-packages\trimesh\io\ply.py", line 225, in ply_ascii
    count].reshape((-1, rows)).astype(dtype)[:, 1:]
ValueError: invalid literal for int() with base 10: '0.188808'

```
Seems like on this one it expects integer colours, but they're given as float's?

Same mesh loading as binary ply:
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2017.1\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\Users\Patrik\Envs\eos-py\lib\site-packages\trimesh\constants.py", line 125, in timed
    result = method(*args, **kwargs)
  File "C:\Users\Patrik\Envs\eos-py\lib\site-packages\trimesh\io\load.py", line 111, in load_mesh
    file_type)
  File "C:\Users\Patrik\Envs\eos-py\lib\site-packages\trimesh\io\ply.py", line 37, in load_ply
    ply_binary(elements, file_obj)
  File "C:\Users\Patrik\Envs\eos-py\lib\site-packages\trimesh\io\ply.py", line 304, in ply_binary
    populate_listsize(file_obj, elements)
  File "C:\Users\Patrik\Envs\eos-py\lib\site-packages\trimesh\io\ply.py", line 267, in populate_listsize
    offset = np.dtype(prior_data).itemsize()
TypeError: 'int' object is not callable

```

I was getting various other errors as well with [this](https://github.com/patrikhuber/eos/blob/master/share/reference_annotated.obj) mesh (after converting it from .obj to .ply with Meshlab) and then trying to load it with trimesh.

Are vertex colours not supported by trimesh?

I'm using Win 10, a virtualenv with python-3.6.1 (64-bit), numpy+mkl, scipy and Shapely from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/), and `pip install trimesh[easy]`.

**Comment by patrikhuber** [comment]
It seems like vertex colours are supported by trimesh, I was able to construct a mesh with the trimesh constructor and it displays with vertex colours in the viewer. So it seems to be like mainly a loading issue.

**Comment by mikedh** [comment]
Hey, thanks for the report.

The OBJ loader in Trimesh definitely doesn't support colors.

The PLY loader does support color, and converting that OBJ you sent to a PLY in meshlab loads with the color correct for me. There's something weird going on, would you mind sending the exact PLY file that is producing these exciting outputs?

**Comment by patrikhuber** [comment]
Hi, thanks for the quick reply! Could I send you the file via email? I'm not sure I can share it publicly.

**Comment by mikedh** [comment]
NP. Email would be good, mik3dh at gmail. One other thing occurs to me- it could be a weird Python 3.6 thing, most of my development machines are on Python 3.5 conda envs that I haven't bothered updating.

**Comment by mikedh** [comment]
Thanks for the examples! This should be fixed for both the binary and ASCII PLY files you sent in https://github.com/mikedh/trimesh/commit/b4829034a900e4401713ecc5bc38906d4ba402ad, you should be able to get it with `pip install --upgrade trimesh`

They were both failing because those files had multiple multi-value properties for faces (vertex index + texcoords). 

The binary one was failing because of a typo introduced at some point, and the ASCII one was failing because that wasn't supported.

**Comment by patrikhuber** [comment]
Cool, working great now, including the vertex colours in the viewer - thank you! :-)
