### ISSUE TITLE
Trimesh.trimesh loading problem?

### ISSUE THREAD

**Issue by vlall** [mikedh/trimesh#491]
Hi, thanks for keeping up this codebase. 

I'm running into an error wile loading in my 3-D numpy arrays

code:
```
import trimesh
from scipy.spatial import Delaunay, ConvexHull
import numpy as np


def is_convex(points):
    # Convert to mesh
    tri = Delaunay(points)
    vertices = points[tri.simplices]
    faces = points[tri.convex_hull]
    print(len(vertices), len(faces))
    mesh = trimesh.Trimesh(vertices=vertices, faces=faces)
    return trimesh.convex.is_convex(mesh)
```
Error:
```Traceback (most recent call last):
  File "filter_topology.py", line 124, in <module>
    if (topography_point_simple(points, normals, i, diameter=160)):
  File "filter_topology.py", line 70, in topography_point_simple
    print(is_convex(filtered_points))
  File "filter_topology.py", line 22, in is_convex
    mesh = trimesh.Trimesh(vertices=vertices, faces=faces)
  File "/Users/vlall/.virtualenvs/m/lib/python3.7/site-packages/trimesh/base.py", line 192, in __init__
    self.process()
  File "/Users/vlall/.virtualenvs/m/lib/python3.7/site-packages/trimesh/base.py", line 224, in process
    self.merge_vertices()
  File "/Users/vlall/.virtualenvs/m/lib/python3.7/site-packages/trimesh/base.py", line 1064, in merge_vertices
    textured=textured)
  File "/Users/vlall/.virtualenvs/m/lib/python3.7/site-packages/trimesh/grouping.py", line 86, in merge_vertices
    digits=digits)
  File "/Users/vlall/.virtualenvs/m/lib/python3.7/site-packages/trimesh/grouping.py", line 412, in unique_rows
    hashes = hashable_rows(data, digits=digits)
  File "/Users/vlall/.virtualenvs/m/lib/python3.7/site-packages/trimesh/grouping.py", line 195, in hashable_rows
    hashable = np.ascontiguousarray(as_int).view(dtype).reshape(-1)
ValueError: When changing to a larger dtype, its size must be a divisor of the total size in bytes of the last axis of the array.
```

(two 3-D example arrays i'm loading as vertices and faces):
```
[[2155.80333528 -805.57846994  460.77698643]
 [2164.78079542 -812.12508442  454.73134122]
 [2164.58326496 -812.07215617  455.59225736]
 ...
 [2556.42965474 -481.21599353  495.62963836]
 [2590.86534961 -567.05348268  455.72165396]
 [2591.42248949 -566.3599159   456.34284848]]
[[[2215.61453802 -496.52809868  682.29917358]
  [2329.65265913 -420.45113189  626.98418945]
  [2234.79995703 -608.30229288  448.50419507]]

 [[2221.4369475  -608.8627819   474.39870179]
  [2125.47648389 -707.96214084  510.27887334]
  [2234.79995703 -608.30229288  448.50419507]]

 [[2221.4369475  -608.8627819   474.39870179]
  [2215.61453802 -496.52809868  682.29917358]
  [2234.79995703 -608.30229288  448.50419507]]

 ...

 [[2467.10033719 -431.39832346  555.8460991 ]
  [2435.50112919 -422.93132046  569.18394232]
  [2379.72431352 -407.98593115  605.16767518]]

 [[2467.10033719 -431.39832346  555.8460991 ]
  [2528.06416651 -447.7335723   515.16346681]
  [2528.28220294 -447.79199512  515.04584839]]

 [[2467.10033719 -431.39832346  555.8460991 ]
  [2526.90785039 -447.42373757  517.0220235 ]
  [2529.01464299 -447.98825232  514.86781478]]]
)
```

**Comment by mikedh** [comment]
Hey, `vertices` takes `(n, 3) float` values, and faces are `(n, 3) int` values referencing `vertices`. You're passing `(n, 3, 3) float` to `vertices`. I think what you want to do is probably something like:
```
    points = np.random.random((1000, 3))
    # Convert to mesh                                                                                
    tri = Delaunay(points)

    mesh = trimesh.Trimesh(vertices=tri.points,
                           faces=tri.convex_hull)
```

Although the function you have above will always return `True`, as you are checking convexity of a convex hull. If you just need the hull of some points as a `Trimesh` object I'd probably recommend something like:
`trimesh.points.PointCloud(points).convex_hull`

If you want to check to see if every point in a list of points lies on the convex hull of that list of points, I'd  check the signed distance of each point from the convex hull:

```
def is_convex(points, epsilon=1e-8):
    """"
    Check to see if every point lies within epsilon of the hull of the points.
    """"
    # get the convex hull as a trimesh.Trimesh object
    hull = trimesh.points.PointCloud(points).convex_hull
    # positive distances are inside the hull, negative are outside
    # every point is inside the hull as that's the definition of a convex hull
    distance = hull.nearest.signed_distance(points)
    # but abs anyway
    on_surface = np.abs(distance) < epsilon
    return on_surface.all()
```

**Comment by vlall** [comment]
Thank you so much for your thorough answer. I'll close this.
