### ISSUE TITLE
Path2D creation raises TypeError

### ISSUE THREAD

**Issue by ELIONET** [mikedh/trimesh#495]
Hi, I'm trying to convert a shapely polygon into a Path2D, but I'm facing an error:

```
p4_1 = Polygon([(89, 302), (130, 234), (143, 177), (163, 116), (236, 74), (250, 250), (361, 138), (384, 189), (374, 251), (526, 360), (281, 273), (275, 294), (252, 414), (189, 369), (179, 319), (156, 302)])

res = trimesh.path.Path2D(trimesh.path.exchange.misc.polygon_to_path(p4_1))
```

Trying to execute this code raises a TypeError :

```
Traceback (most recent call last):

  File "<ipython-input-9-38be51af18b7>", line 1, in <module>
    res = trimesh.path.Path3D(trimesh.path.exchange.misc.polygon_to_path(p4_1))

  File "C:\Users\Emmanuel\Anaconda3\lib\site-packages\trimesh\path\path.py", line 87, in __init__
    self._cache = caching.Cache(id_function=self.crc)

  File "C:\Users\Emmanuel\Anaconda3\lib\site-packages\trimesh\caching.py", line 371, in __init__
    self.id_current = self._id_function()

  File "C:\Users\Emmanuel\Anaconda3\lib\site-packages\trimesh\path\path.py", line 148, in crc
    for e in self.entities))

TypeError: iteration over a 0-d array
```

I'm not sure what is wrong with my code and I would appreciate some help !

**Comment by mikedh** [comment]
Hey, not sure what's up with the error, maybe try:
`res = trimesh.load_path(p4_1)`

It worked OK for me:
```
In [1]: from shapely.geometry import Polygon

In [3]: p4 = Polygon([(89, 302), (130, 234), (143, 177), (163, 116), (236, 74),
   ...:  (250, 250), (361, 138), (384, 189), (374, 251), (526, 360), (281, 273)
   ...: , (275, 294), (252, 414), (189, 369), (179, 319), (156, 302)])

In [4]: p4
Out[4]: <shapely.geometry.polygon.Polygon at 0x235760c0a20>

In [5]: p4.is_valid
Out[5]: True

In [6]: p4.is_closed
Out[6]: False

In [7]: import trimesh

In [8]: m = trimesh.load_path(p4)

In [9]: m
Out[9]: <trimesh.path.path.Path2D at 0x235787ecac8>

In [10]: m.show()
```

**Comment by ELIONET** [comment]
It also worked for me, thanks !

**Comment by ELIONET** [comment]
It also worked for me, thanks !

**Comment by mikedh** [comment]
BTW, the reason the original statement:
`trimesh.path.Path2D(trimesh.path.exchange.misc.polygon_to_path(p4_1))`

didn't work was because `polygon_to_path` returns a dict of kwargs, which you need to load like:
`trimesh.path.Path2D(**trimesh.path.exchange.misc.polygon_to_path(p4_1))`

`trimesh.load_path` is probably easier regardless.
