### ISSUE TITLE
List Index out of Range when loading .obj

### ISSUE THREAD

**Issue by Twali** [mikedh/trimesh#649]
Hi, I am trying to load .obj model that I created with blender but I am having issues. It seems to work fine with .ply or .stl format. The error I keep getting is "Indexerror: list index out of range"

Traceback (most recent call last):
  File ".\pyrenderTest.py", line 14, in <module>
    road = trimesh.load('C:/Users/walit/Downloads/Surface/surface.obj', file_type='OBJ')
  File "C:\Program Files\Python37\lib\site-packages\trimesh\exchange\load.py", line 136, in load
    **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\trimesh\constants.py", line 136, in timed
    result = method(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\trimesh\exchange\load.py", line 212, in load_mesh
    **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\trimesh\exchange\obj.py", line 80, in load_obj
    v, vn, vt, vc = _parse_vertices(text=text)
  File "C:\Program Files\Python37\lib\site-packages\trimesh\exchange\obj.py", line 513, in _parse_vertices
    per_row = {k: len(v[1].split()) for k, v in data.items()}
  File "C:\Program Files\Python37\lib\site-packages\trimesh\exchange\obj.py", line 513, in <dictcomp>
    per_row = {k: len(v[1].split()) for k, v in data.items()}
IndexError: list index out of range

Here is my .obj

# Blender v2.80 (sub 75) OBJ File: ''
# www.blender.org
mtllib surface.mtl

o textureSurface
v -500.000000 0.000000 500.000000
v 500.000000 0.000000 500.000000
v 500.000000 0.000000 -500.000000
v -500.000000 0.000000 -500.000000
vt 0.000000 0.000000
vt 1.000000 0.000000
vt 1.000000 1.000000
vt 0.000000 1.000000
vn 0.0000 1.0000 0.0000
usemtl Material
s 1
f 1/1/1 2/2/1 3/3/1
f 1/1/1 3/3/1 4/4/1

Thank you in advance for you help!

**Comment by Twali** [comment]
It seems like when it its parsing the .obj and attempts to split the row, the index issue comes up. I looked at other issue but no luck so far. I thought maybe it has something to do with spacing

**Comment by mikedh** [comment]
Yeah looks like it is checking the second element to estimate length, which failed on 1-length properties like your `vn` in that example mesh.

**Comment by Twali** [comment]
That works! Thanks for your help.
