### ISSUE TITLE
Scipy updated and broke bounding_box_oriented

### ISSUE THREAD

**Issue by nick-parker** [mikedh/trimesh#670]
I recently rebuilt my docker image based in the latest trimesh base image in docker hub, and now whenever I call bounding_box_oriented I get
```
>>> foo.bounding_box_oriented
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/trimesh/caching.py", line 104, in get_cached
    value = function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trimesh/parent.py", line 141, in bounding_box_oriented
    to_origin, extents = bounds.oriented_bounds(self)
  File "/usr/local/lib/python3.6/site-packages/trimesh/bounds.py", line 140, in oriented_bounds
    if hasattr(obj, 'convex_hull'):
  File "/usr/local/lib/python3.6/site-packages/trimesh/caching.py", line 104, in get_cached
    value = function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trimesh/base.py", line 2100, in convex_hull
    hull = convex.convex_hull(self)
  File "/usr/local/lib/python3.6/site-packages/trimesh/convex.py", line 54, in convex_hull
    qhull_options=qhull_options)
  File "qhull.pyx", line 2428, in scipy.spatial.qhull.ConvexHull.__init__
  File "qhull.pyx", line 357, in scipy.spatial.qhull._Qhull.__init__
scipy.spatial.qhull.QhullError: QH7023 qhull option warning: unknown 'Q' qhull option 'Qn', skip to next space
QH6035 qhull option error: see previous warnings, use 'Qw' to override: 'qhull i Pp Qt QJn QbB' (last offset 15)

While executing:  | qhull i Pp Qt QJn QbB
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 518360264  incidence  Pprecision-ignore  Qtriangulate
  QbBound-unit-box 0.5  _maxoutside  0
```
Doesn't seem to matter what the file is, and files which previously worked now reproduce the issue so I think it's fairly universal.

The issue was introduced in the scipy update released yesterday, version 1.4.0. I'm just sticking with 1.3.3 for now but it'd be nice to stay up to date.

**Comment by mikedh** [comment]
Ah yeah, can reproduce locally with newest scipy. It looks like it's mad at the the `QJn` option, I'll PR shortly. Thanks for the report!
