### ISSUE TITLE
Error when try to run

### ISSUE THREAD

**Issue by vitsensei** [mikedh/trimesh#693]
Hi, I got this error when trying to install trimesh with all soft dependencies through pip command.
Collecting trimesh[easy]
Collecting setuptools (from trimesh[easy])
  Using cached https://files.pythonhosted.org/packages/af/e7/02db816dc88c598281bacebbb7ccf2c9f1a6164942e88f1a0fded8643659/setuptools-45.0.0-py2.py3-none-any.whl
Collecting numpy (from trimesh[easy])
  Using cached https://files.pythonhosted.org/packages/62/20/4d43e141b5bc426ba38274933ef8e76e85c7adea2c321ecf9ebf7421cedf/numpy-1.18.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting rtree; extra == "easy" (from trimesh[easy])
  Using cached https://files.pythonhosted.org/packages/11/1d/42d6904a436076df813d1df632575529991005b33aa82f169f01750e39e4/Rtree-0.9.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-t7hzuss9/rtree/setup.py", line 3, in <module>
        import rtree
      File "/tmp/pip-build-t7hzuss9/rtree/rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "/tmp/pip-build-t7hzuss9/rtree/rtree/index.py", line 6, in <module>
        from . import core
      File "/tmp/pip-build-t7hzuss9/rtree/rtree/core.py", line 145, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
        func = self.__getitem__(name)
      File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: /usr/bin/python3: undefined symbol: Error_GetLastErrorNum
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-t7hzuss9/rtree/

I have successfully installed setuptools-45.0.0
Any help? Thanks.

**Comment by mikedh** [comment]
Hey, that looks like a `rtree` install error, check out their install guide:
https://toblerity.org/rtree/install.html
