### ISSUE TITLE
mesh.facets results in ValueError due to mismatched array shapes

### ISSUE THREAD

**Issue by pmayostendorp** [mikedh/trimesh#713]
For certain meshes, I receive a relatively undiagnosable error when trying to obtain mesh's `.facets` attribute. I am loading the mesh, doing a bit of cleaning and translation, then trying to print `mesh.facets` as below:

```python
    mesh = trimesh.load(file_obj=collada_file, file_type='dae')

    # Post-process a bit so we get all geometries into one big mesh
    mesh_list = mesh.dump()

    for m in mesh_list:
        m.visual = trimesh.visual.ColorVisuals()

    mesh = trimesh.util.concatenate(mesh_list)

    # set up the mesh so all coordinates are positive.
    translate = -mesh.bounds[0]
    mesh.apply_translation(translate)

    # fix bad faces and normals
    mesh.process()
    mesh.fix_normals()

    print('mesh.facets: ', mesh.facets)
```
However, for the mesh in question, I get the following. It seems very similar to issues in #591 
```
Traceback (most recent call last):
  File "/Users/peterostendorp/Documents/XeroHome/sce_reachcodes/xerohome_engine/core.py", line 104, in construct_base_bldg_1
    post_geometry_xml_file)
  File "/Users/peterostendorp/Documents/XeroHome/sce_reachcodes/xerohome_engine/eplus/write_geometry_to_xml.py", line 261, in write_geometry_to_xml
    print('mesh.facets: ', mesh.facets)
  File "/anaconda2/envs/xerohome37/lib/python3.7/site-packages/trimesh/caching.py", line 101, in get_cached
    value = function(*args, **kwargs)
  File "/anaconda2/envs/xerohome37/lib/python3.7/site-packages/trimesh/base.py", line 1590, in facets
    facets = graph.facets(self)
  File "/anaconda2/envs/xerohome37/lib/python3.7/site-packages/trimesh/graph.py", line 279, in facets
    radii = mesh.face_adjacency_radius
  File "/anaconda2/envs/xerohome37/lib/python3.7/site-packages/trimesh/caching.py", line 101, in get_cached
    value = function(*args, **kwargs)
  File "/anaconda2/envs/xerohome37/lib/python3.7/site-packages/trimesh/base.py", line 1379, in face_adjacency_radius
    radii, span = graph.face_adjacency_radius(mesh=self)
  File "/anaconda2/envs/xerohome37/lib/python3.7/site-packages/trimesh/graph.py", line 172, in face_adjacency_radius
    point_pairs = mesh.vertices[mesh.face_adjacency_unshared]
  File "/anaconda2/envs/xerohome37/lib/python3.7/site-packages/trimesh/caching.py", line 101, in get_cached
    value = function(*args, **kwargs)
  File "/anaconda2/envs/xerohome37/lib/python3.7/site-packages/trimesh/base.py", line 1366, in face_adjacency_unshared
    vid_unshared = graph.face_adjacency_unshared(self)
  File "/anaconda2/envs/xerohome37/lib/python3.7/site-packages/trimesh/graph.py", line 140, in face_adjacency_unshared
    vid_unshared[:, i] = faces[np.logical_not(shared)]
ValueError: could not broadcast input array from shape (130) into shape (131)
```
I'm using trimesh version 3.1.11. Thanks for any thoughts! Attached the .dae in a .zip.
[SM_90402_A_00003141.dae.zip](https://github.com/mikedh/trimesh/files/4173587/SM_90402_A_00003141.dae.zip)

**Comment by mikedh** [comment]
Thanks for the report! I was able to reproduce your issue using `trimesh==3.1.11`. The issue appears to be fixed however in newer versions of trimesh (the `face_adjacency_unshared` function was refactored significantly). 

Are you able to upgrade to a newer version of trimesh? `pip install --upgrade trimesh`

**Comment by pmayostendorp** [comment]
Mike thanks for looking into this on the weekend and checking right away. Was trying not to fiddle too much with my environment, but upgrading to 3.5.20 did the trick.
