### ISSUE TITLE
'function' object has not attribute 'connected_components'

### ISSUE THREAD

**Issue by gyanendra-d-tripathi** [mikedh/trimesh#750]
I am using trimesh.load_mesh() to load my object file. After that I call mesh.fix_normals() and python shows following error:
The same code works in Jupyter Notebook but when running in windows 10 command prompt using python 3.7 this error comes. I can't use Jupyter notebook for entire project because it is not working nicely with vtkplotter.
I would appreciate help from any one:
C:\Users\gyane\proj3_starter>python grasping.py
Traceback (most recent call last):
  File "grasping.py", line 322, in <module>
    main()
  File "grasping.py", line 308, in main
    mesh = load_mesh(obj)
  File "grasping.py", line 297, in load_mesh
    mesh.fix_normals()
  File "C:\Users\gyane\AppData\Local\Programs\Python\Python37\lib\site-packages\trimesh\constants.py", line 134, in timed
    result = method(*args, **kwargs)
  File "C:\Users\gyane\AppData\Local\Programs\Python\Python37\lib\site-packages\trimesh\base.py", line 1776, in fix_normals
    multibody = self.body_count > 1
  File "C:\Users\gyane\AppData\Local\Programs\Python\Python37\lib\site-packages\trimesh\caching.py", line 103, in get_cached
    value = function(*args, **kwargs)
  File "C:\Users\gyane\AppData\Local\Programs\Python\Python37\lib\site-packages\trimesh\base.py", line 973, in body_count
    count, labels = graph.csgraph.connected_components(
AttributeError: 'function' object has no attribute 'connected_components'

**Comment by mikedh** [comment]
Hey, this is probably due to not having `scipy` installed (`pip install scipy`). It should have re-raised the `ImportError` however, which I fixed in #756 

Thanks for the report

**Comment by gyanendra-d-tripathi** [comment]
Thanks Mikedh. Now it worked. Hope to complete my project.
