### ISSUE TITLE
examples/viewcallback.py render only second sphere

### ISSUE THREAD

**Issue by USSRcoder** [mikedh/trimesh#802]
win8, py3.8 embeded;

> examples/viewcallback.py 

render only second sphere (blue);

> examples/voxel.py crashed 

Traceback (most recent call last):
  File "testmesh.py", line 83, in <module>
    voxelized = chair_mesh.voxelized(pitch=0.02, method='binvox')
  File "C:\Python38\lib\site-packages\trimesh\base.py", line 2287, in voxelized
    return creation.voxelize(
  File "C:\Python38\lib\site-packages\trimesh\voxel\creation.py", line 300, in voxelize
    return voxelizers(method, mesh=mesh, pitch=pitch, **kwargs)
  File "C:\Python38\lib\site-packages\trimesh\util.py", line 2187, in __call__
    return self[key](*args, **kwargs)
  File "C:\Python38\lib\site-packages\trimesh\constants.py", line 134, in timed
    result = method(*args, **kwargs)
  File "C:\Python38\lib\site-packages\trimesh\voxel\creation.py", line 270, in voxelize_binvox
    return binvox.voxelize_mesh(mesh, binvoxer)
  File "C:\Python38\lib\site-packages\trimesh\exchange\binvox.py", line 574, in voxelize_mesh
    with open(out_path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\adm\\AppData\\Local\\Temp\\tmp09kh2moa\\model.binvox'

file C:\Users\adm\AppData\Local\Temp\tmp09kh2moa\model.off,
file C:\Users\adm\AppData\Local\Temp\tmp09kh2moa\model.binvox not created; 
binvox in the path and worked (previus simples passed);

> examples/voxel_silhouette.py

Traceback (most recent call last):
  File "testmesh.py", line 18, in <module>
    origin, rays = scene.camera_rays()
ValueError: too many values to unpack (expected 2)

after patch this to 
`origin, rays, px = scene.camera_rays()`

Traceback (most recent call last):
  File "testmesh.py", line 20, in <module>
    offset = mesh.vertices - origin
ValueError: operands could not be broadcast together with shapes (8146,3) (65536,3)

**Comment by mikedh** [comment]
Thanks for the report! I fixed the issues with `viewcallback.py` and `voxel_sillhoutte.py`. `voxels.py` seemed to be running OK without changes.
