### ISSUE TITLE
I measure the volume, but get a wrong result...

### ISSUE THREAD

**Issue by a740615405** [mikedh/trimesh#918]
[Part2.zip](https://github.com/mikedh/trimesh/files/4916464/Part2.zip)
I use the following code to load a mesh and cut it with a plane, then I measure the volume, but I get the wrong result, 
when I change the direction of (1,0,-3.33), I event get a minus. What's wrong with this?

a = trimesh.load_mesh('Part2.stl')
after_split = a.slice_plane((2170, -285, 60), (1,0,-3.33))
shape_volume = after_split.volume / 1000000
print(shape_volume)

I get a result of 186.9L, but the whole volume is 75.5L. when I change the direction of (1,0,-3.33), I event get a minus. Why?

**Comment by mikedh** [comment]
Hey, volume is only valid for watertight meshes. When you slice it you probably need to cap the slice to make that result watertight and thus have valid volume.

**Comment by a740615405** [comment]
> Hey, volume is only valid for watertight meshes. When you slice it you probably need to cap the slice to make that result watertight and thus have valid volume.

Hello mikedh:
Thank you for replying. 
But I am a new person to study trimesh, how can I cap the slice?
And I have tried a simple model, such as I draw a cuboid, and run the code, that will be ok to work. Why?

**Comment by mikedh** [comment]
Hey, try passing `cap=True`:

```
In [1]: import trimesh

In [2]: m = trimesh.creation.box()

In [3]: m.volume
Out[3]: 1.0

In [5]: sliced = m.slice_plane(plane_origin=m.center_mass, plane_normal=[0,0,1], cap=True)
```

**Comment by a740615405** [comment]
> Hey, try passing `cap=True`:
> 
> ```
> In [1]: import trimesh
> 
> In [2]: m = trimesh.creation.box()
> 
> In [3]: m.volume
> Out[3]: 1.0
> 
> In [5]: sliced = m.slice_plane(plane_origin=m.center_mass, plane_normal=[0,0,1], cap=True)
> ```

Hello @mikedh :
I tied your suggestion, but I get a wrong Traceback:
sliced = m.slice_plane(plane_origin=m.center_mass, plane_normal=[0,0,1], cap=True)

Traceback (most recent call last):
  File "D:/3D data study software/3D management/fuckj.py", line 10, in <module>
    sliced = m.slice_plane(plane_origin=m.center_mass, plane_normal=[0,0,1], cap=True)
  File "C:\Program Files\Anaconda3\lib\site-packages\trimesh\base.py", line 2097, in slice_plane
    **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\trimesh\intersections.py", line 683, in slice_mesh_plane
    cached_dots=dots)
  File "C:\Program Files\Anaconda3\lib\site-packages\trimesh\base.py", line 2017, in section
    path = load_path(lines)
  File "C:\Program Files\Anaconda3\lib\site-packages\trimesh\exchange\load.py", line 45, in load_path
    raise _path_exception
  File "C:\Program Files\Anaconda3\lib\site-packages\trimesh\exchange\load.py", line 29, in <module>
    from ..path.exchange.load import load_path, path_formats
  File "C:\Program Files\Anaconda3\lib\site-packages\trimesh\path\__init__.py", line 1, in <module>
    from .path import Path2D, Path3D
  File "C:\Program Files\Anaconda3\lib\site-packages\trimesh\path\path.py", line 33, in <module>
    from . import polygons
  File "C:\Program Files\Anaconda3\lib\site-packages\trimesh\path\polygons.py", line 3, in <module>
    from shapely import ops
ImportError: No module named 'shapely'

But if I tried this, that will work:
sliced = m.slice_plane(m.center_mass, [0,0,1])
The shape can't be caped?

**Comment by mikedh** [comment]
Nah you're missing `shapely` and probably also `triangle`:

`pip install shapely triangle`

**Comment by a740615405** [comment]
> Nah you're missing `shapely` and probably also `triangle`:
> 
> `pip install shapely triangle`

Hello @mikedh :
I just install the shapely and triangle, but also don't work.

import trimesh
import shapely
import triangle
m = trimesh.creation.box()
print(m.volume)
sliced = m.slice_plane(plane_origin=m.center_mass, plane_normal=[0,0,1], cap=True)
# sliced = m.slice_plane(m.center_mass, [0,0,1])
print(sliced.volume)

1.0
Traceback (most recent call last):
  File "D:/3D data study software/3D management/fuckj.py", line 12, in <module>
    sliced = m.slice_plane(plane_origin=m.center_mass, plane_normal=[0,0,1], cap=True)
  File "C:\Program Files\Anaconda3\lib\site-packages\trimesh\base.py", line 2097, in slice_plane
    **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\trimesh\intersections.py", line 683, in slice_mesh_plane
    cached_dots=dots)
  File "C:\Program Files\Anaconda3\lib\site-packages\trimesh\base.py", line 2017, in section
    path = load_path(lines)
  File "C:\Program Files\Anaconda3\lib\site-packages\trimesh\exchange\load.py", line 45, in load_path
    raise _path_exception
  File "C:\Program Files\Anaconda3\lib\site-packages\trimesh\exchange\load.py", line 29, in <module>
    from ..path.exchange.load import load_path, path_formats
  File "C:\Program Files\Anaconda3\lib\site-packages\trimesh\path\__init__.py", line 1, in <module>
    from .path import Path2D, Path3D
  File "C:\Program Files\Anaconda3\lib\site-packages\trimesh\path\path.py", line 33, in <module>
    from . import polygons
  File "C:\Program Files\Anaconda3\lib\site-packages\trimesh\path\polygons.py", line 3, in <module>
    from shapely import ops
  File "C:\Program Files\Anaconda3\lib\site-packages\shapely\ops.py", line 13, in <module>
    from shapely.geos import lgeos
  File "C:\Program Files\Anaconda3\lib\site-packages\shapely\geos.py", line 145, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "C:\Program Files\Anaconda3\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by mikedh** [comment]
Ah your `shapely` install is still busted... you might try it with conda: `conda install -c conda-forge shapely`

**Comment by a740615405** [comment]
> Ah your `shapely` install is still busted... you might try it with conda: `conda install -c conda-forge shapely`

Hi @mikedh :
That worked, thank you very very much!
