### ISSUE TITLE
Scene save_image gives ZeroDivisionErrors and other random process exits after multitude of calls

### ISSUE THREAD

**Issue by EenKnurft** [mikedh/trimesh#936]
Hi! 

First of all, awesome library! I am currently using it to create multi view snapshots of geometries. Unfortunately, after a while of calling the scene.save_image method a couple of times issues occur: a random ZeroDivisionError and a random Process exit. 

Using the following script, which just tries to make 1000 of the same images crashes for the first time after iteration `i=129`.
After around 446 iterations python crashes completely and it returns 'Process finished with exit code -1073740771 (0xC000041D)' Here the exit codes are different every time. 
I do not see the memory/CPU/GPU statistics blowing up in the task manager. 

```
import trimesh

for i in range(1000):

    print(i)

    try:
        stl = trimesh.load('C:/Local/Workspace/some_geometry.stl')

        scene = trimesh.Scene(stl)

        with open('C:/Local/Workspace/some_geometry.png', 'wb') as f:
            f.write(scene.save_image(resolution=[512, 512], visible=True))
            f.close()

    except ZeroDivisionError:
        print("ZERO DIVISION ERROR at i =", i)
```

result:

```
1
2
3
...
127
128
129
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 237, in 'calling callback function'
  File "C:\Users\...\AppData\Roaming\Python\Python38\site-packages\pyglet\window\win32\__init__.py", line 712, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\...\AppData\Roaming\Python\Python38\site-packages\pyglet\window\win32\__init__.py", line 1049, in _event_size
    self.dispatch_event('on_resize', self._width, self._height)
  File "C:\Users\...\AppData\Roaming\Python\Python38\site-packages\pyglet\window\__init__.py", line 1333, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\...\AppData\Roaming\Python\Python38\site-packages\pyglet\event.py", line 415, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Users\...\AppData\Roaming\Python\Python38\site-packages\trimesh\viewer\windowed.py", line 583, in on_resize
    width, height = self._update_perspective(width, height)
  File "C:\Users\NEGGINK\AppData\Roaming\Python\Python38\site-packages\trimesh\viewer\windowed.py", line 572, in _update_perspective
    width / float(height),
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "C:/Local/Repositories/modularization/test.py", line 12, in <module>
    f.write(scene.save_image(resolution=[512, 512], visible=True))
  File "C:\Users\...\AppData\Roaming\Python\Python38\site-packages\trimesh\scene\scene.py", line 852, in save_image
    png = render_scene(scene=self,
  File "C:\Users\...\AppData\Roaming\Python\Python38\site-packages\trimesh\viewer\windowed.py", line 857, in render_scene
    window.dispatch_events()
  File "C:\Users\...\AppData\Roaming\Python\Python38\site-packages\pyglet\window\win32\__init__.py", line 688, in dispatch_events
    self.dispatch_pending_events()
  File "C:\Users\...\AppData\Roaming\Python\Python38\site-packages\pyglet\window\win32\__init__.py", line 704, in dispatch_pending_events
    event[0](*event[1:])
  File "C:\Users\...\AppData\Roaming\Python\Python38\site-packages\pyglet\window\win32\__init__.py", line 1049, in _event_size
    self.dispatch_event('on_resize', self._width, self._height)
  File "C:\Users\NEGGINK\AppData\Roaming\Python\Python38\site-packages\pyglet\window\__init__.py", line 1333, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\...\AppData\Roaming\Python\Python38\site-packages\pyglet\event.py", line 415, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Users\...\AppData\Roaming\Python\Python38\site-packages\trimesh\viewer\windowed.py", line 583, in on_resize
    width, height = self._update_perspective(width, height)
  File "C:\Users\...\AppData\Roaming\Python\Python38\site-packages\trimesh\viewer\windowed.py", line 572, in _update_perspective
    width / float(height),
ZeroDivisionError: float division by zero
130
131
132
...
446

Process finished with exit code -1073740771 (0xC000041D)
```

Do you have an idea what the problem could be. I suspect is has something to do with memory allocation, but am unable to solve it.

Much thanks in advance!

**Comment by mikedh** [comment]
That's interesting! Looks like the Pyglet event is sending a zero-height resize event... we could do input validation and cancel the resize if any value is zero, but I suspect this is to do with the wider issue in long-running Python programs. You might check out #171 (most people on Stackoverflow suggest restarting a process every now and then).

**Comment by EenKnurft** [comment]
Thanks @mikedh! the Multiprocess solution did the trick. The performance of the application took a massive hit, but the output is as expected :)

**Comment by BCoxford** [comment]
Hi!

As you said you get an error when updating the perspective.

A potential fix to this would be to focus the camera on the object/point when rendering an image, instead of changing the perspective using the existing function 'update_perspective'. 

You can even use existing code to do this. I've used this method instead to render multiple images.

```
center = mesh.centroid #Centre Point of Mesh (x, y, z)
scene.set_camera(center=center)
```
