### ISSUE TITLE
Support for pyinstaller?

### ISSUE THREAD

**Issue by vitsensei** [mikedh/trimesh#944]
Hi Mike,
Awesome library. I developed my software around your package and now trying to make an executable out of it using pyinstaller. However, as I was running it, I got this error:

```
Traceback (most recent call last):
  File "Project.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\anh tran\pycharmprojects\waamsoft_python\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "Core\Parts.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\anh tran\pycharmprojects\waamsoft_python\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\trimesh\__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\anh tran\pycharmprojects\waamsoft_python\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\trimesh\base.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\anh tran\pycharmprojects\waamsoft_python\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\trimesh\units.py", line 15, in <module>
  File "lib\site-packages\trimesh\resources\__init__.py", line 34, in get
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ANHTRA~1\\AppData\\Local\\Temp\\_MEI10042\\trimesh\\resources\\units_to_inches.json'
[7928] Failed to execute script Project
```
I believe this is not a new problem, as I can see at least one instance of this issue in the past. I just wonder how are we going with this? Thanks :D.

Edit: I used Pycharm. Not sure if using a virtual environment has anything to do with this...

**Comment by vitsensei** [comment]
Hey @mikedh, I found a solution from here: https://github.com/pyinstaller/pyinstaller/issues/5056
I'm not sure how you would fix this though, just putting it here as future reference :).
