### ISSUE TITLE
Loading from Collada Ignores Scene Transform

### ISSUE THREAD

**Issue by fishyai** [mikedh/trimesh#954]
Hi,

I'm using trimesh to load the mesh from a .dae file (it's the mesh for a Franka Panda robot link), but the origin is different in the mesh is different after I load it with trimesh than it is in meshlab. From some digging around in the .dae file (attached), I believe it's because there is section toward the bottom of the xml file that has this: 
```
  <library_visual_scenes>
    <visual_scene id="Scene" name="Scene">
      <node id="node0" name="node0" type="NODE">
        <matrix sid="transform">1 0 0 0 0 1 0 0 0 0 1 -0.192 0 0 0 1</matrix>
        <instance_geometry url="#Part__Feature_001-mesh" name="node0">
          <bind_material>
            <technique_common>
              <instance_material symbol="Part__Feature_001-material" target="#Part__Feature_001-material"/>
            </technique_common>
          </bind_material>
        </instance_geometry>
      </node>
    </visual_scene>
  </library_visual_scenes>
```

I've been loading the file by doing the following:
```
import trimesh
kwargs = trimesh.exchange.dae.load_collada(PATH_TO_FILE)
m = trimesh.exchange.load.load_kwargs(kwargs)
meshes = []
for g in m.geometry.values():
    meshes.append(trimesh.Trimesh(vertices=g.vertices, faces=g.faces))
mesh = trimesh.util.concatenate(meshes)
```
This seems to lead to an incorrectly set origin.

But, I've been able to get around this by manually parsing the collada file and applying the transform myself. The following snippet produces the correct mesh, but it's very haphazard:
```
import trimesh
import collada
kwargs = trimesh.exchange.dae.load_collada(PATH_TO_FILE)
m = trimesh.exchange.load.load_kwargs(kwargs)
mesh = collada.Collada(PATH_TO_FILE)
n = mesh.scenes[0].nodes[0]
transform = n.transforms[0].matrix
m.apply_transform(transform)
meshes = []
for g in m.geometry.values():
    meshes.append(trimesh.Trimesh(vertices=g.vertices, faces=g.faces))
mesh = trimesh.util.concatenate(meshes)
```

Is there some more principled way to properly load a collada file?

[link1.zip](https://github.com/mikedh/trimesh/files/5076305/link1.zip)

**Comment by mikedh** [comment]
Hey, I don't know if it's doing the correct thing currently but I would load the file like this:

`mesh = trimesh.load(PATH_TO_FILE, force='mesh')`

I'll take a look at the transform issue, thanks for the report!

**Comment by mikedh** [comment]
On a quick look it looks like it's getting the transform that matches the XML:

```
In [2]: s = trimesh.load('/home/mikedh/Downloads/link1.zip')

In [3]: s
Out[3]: <trimesh.Scene(len(geometry)=1)>

In [4]: s.show()
Out[4]: SceneViewer(width=1800, height=1350)

In [5]: s
Out[5]: <trimesh.Scene(len(geometry)=1)>

In [6]: s.bounds
Out[6]: 
array([[-0.05501461, -0.129392  , -0.192     ],
       [ 0.05500113,  0.05501437,  0.05500239]])

In [7]: s.graph
Out[7]: <trimesh.scene.transforms.TransformForest at 0x7f9b493a9a10>

In [8]: s.graph.nodes
Out[8]: 
['world',
 'Part__Feature_001-mesh.0',
 'camera_FWTDTQ',
 'light_GGVLUO',
 'light_GGSSMN']

In [9]: 

In [9]: 

In [9]: s.graph['Part__Feature_001-mesh.0']
Out[9]: 
(array([[ 1.   ,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  1.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  1.   , -0.192],
        [ 0.   ,  0.   ,  0.   ,  1.   ]]), 'Part__Feature_001-mesh.0')


In [11]: s.dump(concatenate=True)
Out[11]: <trimesh.Trimesh(vertices.shape=(34555, 3), faces.shape=(12516, 3))>


```

**Comment by fishyai** [comment]
Oh hey! That works! This is great and way easier. Thank you for you help!

**Comment by fishyai** [comment]
@mikedh just a quick question on that: when you load the mesh that way, do you get weird errors about texture? When I load it as you suggested, I first got a non-blocking complaint asking me to install shapely. Then, when I installed shapely, I got this (also nonblocking)

concatenating texture: may result in visual artifacts
failed to combine visuals
```
Traceback (most recent call last):
  File "/home/fishy/anaconda3/envs/mogul/lib/python3.8/site-packages/trimesh/util.py", line 1431, in concatenate
    visual = meshes[0].visual.concatenate(
  File "/home/fishy/anaconda3/envs/mogul/lib/python3.8/site-packages/trimesh/visual/texture.py", line 209, in concatenate
    return concatenate(self, others)
  File "/home/fishy/anaconda3/envs/mogul/lib/python3.8/site-packages/trimesh/visual/objects.py", line 80, in concatenate
    new_mat, new_uv = pack(materials=mats, uvs=uvs)
  File "/home/fishy/anaconda3/envs/mogul/lib/python3.8/site-packages/trimesh/visual/material.py", line 435, in pack
    [new_uv.append((uvs[i] * scale) + uv_off) for i in idxs]
  File "/home/fishy/anaconda3/envs/mogul/lib/python3.8/site-packages/trimesh/visual/material.py", line 435, in <listcomp>
    [new_uv.append((uvs[i] * scale) + uv_off) for i in idxs]
ValueError: operands could not be broadcast together with shapes (0,) (2,) 
```
