### ISSUE TITLE
problem processing custom .ply files

### ISSUE THREAD

**Issue by ttsesm** [mikedh/trimesh#969]
Hi @mikedh,

I want to load a custom .ply file with different properties and elements structured in the following format:

```
File: map_mesh.ply
Description:
ply
format binary_little_endian 1.0
comment generated by omnimap
element vertex 3786298
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float radiance_blue
property float radiance_green
property float radiance_red
property float irradiance_blue
property float irradiance_green
property float irradiance_red
property float irradiance_lamp_0_blue
property float irradiance_lamp_0_green
property float irradiance_lamp_0_red
property float irradiance_lamp_1_blue
property float irradiance_lamp_1_green
property float irradiance_lamp_1_red
property float irradiance_lamp_2_blue
property float irradiance_lamp_2_green
property float irradiance_lamp_2_red
property float irradiance_lamp_3_blue
property float irradiance_lamp_3_green
property float irradiance_lamp_3_red
property float irradiance_lamp_4_blue
property float irradiance_lamp_4_green
property float irradiance_lamp_4_red
property float irradiance_lamp_5_blue
property float irradiance_lamp_5_green
property float irradiance_lamp_5_red
property float reflectance_blue
property float reflectance_green
property float reflectance_red
element face 7570727
property list uchar uint vertex_indices
element lamp 6
property list uint uint vertex_indices
end_header
```

I've tried to use the following command `mesh = trimesh.exchange.ply.load_ply('map_mesh.ply')` but I am getting the following error:

```
Traceback (most recent call last):
  File "/usr/share/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/usr/share/pycharm/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/ttsesm/Development/open3d_reconstruction_system/3d_reconstruction.py", line 80, in <module>
    test = trimesh.exchange.ply.load_ply(input_file)
  File "/home/ttsesm/Development/open3d_reconstruction_system/venv/lib/python3.8/site-packages/trimesh/exchange/ply.py", line 75, in load_ply
    elements, is_ascii, image_name = parse_header(file_obj)
  File "/home/ttsesm/Development/open3d_reconstruction_system/venv/lib/python3.8/site-packages/trimesh/exchange/ply.py", line 236, in parse_header
    if 'ply' not in str(file_obj.readline()):
AttributeError: 'str' object has no attribute 'readline'
```
Any idea what could be wrong?

You can access the .ply file from [this tarball](http://tracklam.informatik.uni-freiburg.de/downloads/tracklam_ds1_lam.tar.gz) (apologies for the big size).

**Comment by mikedh** [comment]
Hey, I think you just want:
`trimesh.load('map_mesh.ply')`

Using the loader directly is probably not what you want as they are designed to be separable (i.e take only file objects and return dicts with kwargs), where the `trimesh.load` mission statement is "take anything and return geometry." Other quick points:

1) You can load zip/tar.gz files directly with `m = trimesh.load('tracklam_ds1_lam.tar.gz')`
2) I'm not sure how the parser is going to handle the custom format (possibly badly) 
3) When I was testing your custom dtype one of the elements failed:
```
In [1]: import trimesh

In [2]: m = trimesh.load('tracklam_ds1_lam.tar.gz')
PLY failed to populate: lamp

In [3]: m
Out[3]: <trimesh.Scene(len(geometry)=1)>

In [4]: m.geometry
Out[4]: 
OrderedDict([('geometry_0',
              <trimesh.Trimesh(vertices.shape=(3786298, 3), faces.shape=(7570727, 3))>)])
```
In order to get your file to load I had to comment out the file length check and add https://github.com/mikedh/trimesh/pull/967/commits/344a7926338981bcd6fb7a9ff6f29d83f61b679b, which seems like it probably resulted in corrupt results.

**Comment by ttsesm** [comment]
Yes, it is failing to load the `lamp` element. 

Is it possible that I use the [`trimesh.exchange.ply.ply_binary`](https://trimsh.org/trimesh.exchange.ply.html#trimesh.exchange.ply.ply_binary) function instead to load the mesh as dictionary? If yes would you mind to explain how.
