### ISSUE TITLE
Error while loading mesh

### ISSUE THREAD

**Issue by MChaus** [mikedh/trimesh#974]
Hello!
Every time I call this function `trimesh.load(MESH, force='mesh', skip_texture=True)` I get an error message listed below:

> concatenating texture: may result in visual artifacts
failed to combine visuals
Traceback (most recent call last):
  File "/home/mykhailo/anaconda3/envs/my_env/lib/python3.8/site-packages/trimesh/util.py", line 1435, in concatenate
    visual = meshes[0].visual.concatenate(
  File "/home/mykhailo/anaconda3/envs/my_env/lib/python3.8/site-packages/trimesh/visual/texture.py", line 209, in concatenate
    return concatenate(self, others)
  File "/home/mykhailo/anaconda3/envs/my_env/lib/python3.8/site-packages/trimesh/visual/objects.py", line 80, in concatenate
    new_mat, new_uv = pack(materials=mats, uvs=uvs)
  File "/home/mykhailo/anaconda3/envs/my_env/lib/python3.8/site-packages/trimesh/visual/material.py", line 420, in pack
    final, offsets = packing.images(images, power_resize=True)
  File "/home/mykhailo/anaconda3/envs/my_env/lib/python3.8/site-packages/trimesh/path/packing.py", line 429, in images
    rect = np.array([i.size for i in images])
  File "/home/mykhailo/anaconda3/envs/my_env/lib/python3.8/site-packages/trimesh/path/packing.py", line 429, in <listcomp>
    rect = np.array([i.size for i in images])
AttributeError: 'NoneType' object has no attribute 'size'

I am new to trimesh. Can you help me how to avoid this error message.
I've tried
```
mesh = trimesh.load_mesh(MESH)
mesh = mesh.dump().sum()
```
But this has the same effect.

**Comment by MChaus** [comment]
I didn’t mention, but I don’t really need visuals. So, may be I can somehow delete them from scene object?

**Comment by mikedh** [comment]
Hey,  it's probably failing to load images. Have you tried `skip_materials=True` rather than `skip_texture`?

**Comment by MChaus** [comment]
I have just tried and it works fine. Thank you!
I just have this messages:
`specified material (material_3_24)  not loaded!
specified material (material_2_24)  not loaded!
specified material (material_0_24)  not loaded!`
Is there any additional parameter to hide them?

**Comment by MChaus** [comment]
Looks like I found possible solution:

```
log = logging.getLogger('trimesh')
file_handler = logging.FileHandler('trimesh_logs.log')
log.addHandler(file_handler)
```
