### ISSUE TITLE
ModuleNotFoundError: No module named 'networkx'

### ISSUE THREAD

**Issue by nchminaya** [mikedh/trimesh#984]
I installed trimesh in conda in Ubuntu O.S. 
That error pops up when I used mesh.fix_normals() .

  File "repairMesh.py", line 22, in meshRepair
    mesh.fix_normals() 
  File "/.conda/envs/ml/lib/python3.7/site-packages/trimesh/constants.py", line 134, in timed
    result = method(*args, **kwargs)
  File "/.conda/envs/ml/lib/python3.7/site-packages/trimesh/base.py", line 1777, in fix_normals
    repair.fix_normals(self, multibody=multibody)
  File "/.conda/envs/ml/lib/python3.7/site-packages/trimesh/repair.py", line 164, in fix_normals
    fix_winding(mesh)
  File "/.conda/envs/ml/lib/python3.7/site-packages/trimesh/repair.py", line 45, in fix_winding
    graph_all = nx.from_edgelist(mesh.face_adjacency)
  File "/.conda/envs/ml/lib/python3.7/site-packages/trimesh/exceptions.py", line 28, in __getattribute__
    raise super(ExceptionModule, self).__getattribute__('exc')
  File "/.conda/envs/ml/lib/python3.7/site-packages/trimesh/repair.py", line 19, in <module>
    import networkx as nx

Also I tried to reinstall trimesh using: pip install trimesh[all]
It shows this error :

Collecting rtree; extra == "all" (from trimesh[all])
  Using cached https://files.pythonhosted.org/packages/56/6f/f1e91001d5ad9fa9bed65875152f5a1c7955c5763168cae309546e6e9fda/Rtree-0.9.4.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8oo80d2k/rtree/setup.py", line 3, in <module>
        import rtree
      File "/tmp/pip-install-8oo80d2k/rtree/rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "/tmp/pip-install-8oo80d2k/rtree/rtree/index.py", line 6, in <module>
        from . import core
      File "/tmp/pip-install-8oo80d2k/rtree/rtree/core.py", line 143, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/.conda/envs/ml/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
        func = self.__getitem__(name)
      File "/.conda/envs/ml/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: /.conda/envs/ml/bin/python: undefined symbol: Error_GetLastErrorNum
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-8oo80d2k/rtree/

**Comment by mikedh** [comment]
Hey, not sure why conda isn't installing it ([it is in the run_constrained](https://github.com/conda-forge/trimesh-feedstock/blob/5b0dd8ae9c1539857bc5411f0a8a7716e49ddbc5/recipe/meta.yaml#L43)) but you could just run `pip install networkx`.

Yeah `rtree` isn't installing because there aren't wheels on pypi yet, although that is a [work in progress](https://github.com/Toblerity/rtree/pull/163). In the meantime if you install `sudo apt-get install libspatialindex-dev` before `pip install rtree` it should succeed.

**Comment by nchminaya** [comment]
I tried with pip install networkx. 
It works, thanks!
